//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace DS.Showdown.SharedForms
{
	/// <summary>
	/// Summary description for ShowBatterForm.
	/// </summary>

	partial class ShowBatterForm : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Button btnIdok;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.Label lblPosition1;
        private System.Windows.Forms.Label lblPosition2;
        private System.Windows.Forms.Label lblStatic2;
        private System.Windows.Forms.Label lblPoints;
        private System.Windows.Forms.GroupBox grpStatic3;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.Label lblStatic5;
        private System.Windows.Forms.Label lblStatic6;
        private System.Windows.Forms.Label lblStatic7;
        private System.Windows.Forms.Label lblStatic8;
        private System.Windows.Forms.Label lblStatic9;
        private System.Windows.Forms.Label lblStatic10;
        private System.Windows.Forms.Label lblStatic11;
        private System.Windows.Forms.Label lblStatic12;
        private System.Windows.Forms.Label lblStatic13;
        private System.Windows.Forms.GroupBox grpStatic14;
        private System.Windows.Forms.Label lblStatic15;
        private System.Windows.Forms.Label lblStatic16;
        private System.Windows.Forms.Label lblStatic17;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.Label lblStatic18;
        private System.Windows.Forms.Label lblStatic19;
        private System.Windows.Forms.Label lblSpeed;
        private System.Windows.Forms.Label lblOnbase;
        private System.Windows.Forms.Label lblBats;
        private System.Windows.Forms.Label lblStatic20;
        private System.Windows.Forms.Label lblStatic21;
        private System.Windows.Forms.Label lblStatic22;
        private System.Windows.Forms.Label lblStatic23;
        private System.Windows.Forms.Label lblStatic24;
        private System.Windows.Forms.Label lblStatic25;
        private System.Windows.Forms.Label lblStatic26;
        private System.Windows.Forms.Label lblStatic27;
        private System.Windows.Forms.Label lblStatic28;
        private System.Windows.Forms.Label lblStatic29;
        private System.Windows.Forms.Label lblStatic30;
        private System.Windows.Forms.Label lblStatic31;
        private System.Windows.Forms.Label lblStatic32;
        private System.Windows.Forms.Label lblStatic33;
        private System.Windows.Forms.Label lblAbseason;
        private System.Windows.Forms.Label lblHseason;
        private System.Windows.Forms.Label lbl2bseason;
        private System.Windows.Forms.Label lbl3bseason;
        private System.Windows.Forms.Label lblHrseason;
        private System.Windows.Forms.Label lblRseason;
        private System.Windows.Forms.Label lblRbiseason;
        private System.Windows.Forms.Label lblSacseason;
        private System.Windows.Forms.Label lblSbseason;
        private System.Windows.Forms.Label lblKseason;
        private System.Windows.Forms.Label lblBbseason;
        private System.Windows.Forms.Label lblAvgseason;
        private System.Windows.Forms.Label lblObpseason;
        private System.Windows.Forms.Label lblSlugseason;
        private System.Windows.Forms.Label lblRangepu;
        private System.Windows.Forms.Label lblRangeso;
        private System.Windows.Forms.Label lblRangegb;
        private System.Windows.Forms.Label lblRangefo;
        private System.Windows.Forms.Label lblRangew;
        private System.Windows.Forms.Label lblRange1b;
        private System.Windows.Forms.Label lblRange1bplus;
        private System.Windows.Forms.Label lblRange2b;
        private System.Windows.Forms.Label lblRange3b;
        private System.Windows.Forms.Label lblRangehr;
        private System.Windows.Forms.Label lblAbgame;
        private System.Windows.Forms.Label lblHgame;
        private System.Windows.Forms.Label lbl2bgame;
        private System.Windows.Forms.Label lbl3bgame;
        private System.Windows.Forms.Label lblHrgame;
        private System.Windows.Forms.Label lblRgame;
        private System.Windows.Forms.Label lblRbigame;
        private System.Windows.Forms.Label lblSacgame;
        private System.Windows.Forms.Label lblSbgame;
        private System.Windows.Forms.Label lblKgame;
        private System.Windows.Forms.Label lblBbgame;
        private System.Windows.Forms.Label lblAvggame;
        private System.Windows.Forms.Label lblObpgame;
        private System.Windows.Forms.Label lblSluggame;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.btnIdok = new System.Windows.Forms.Button();
			this.lblStatic1 = new System.Windows.Forms.Label();
			this.lblPosition1 = new System.Windows.Forms.Label();
			this.lblPosition2 = new System.Windows.Forms.Label();
			this.lblStatic2 = new System.Windows.Forms.Label();
			this.lblPoints = new System.Windows.Forms.Label();
			this.grpStatic3 = new System.Windows.Forms.GroupBox();
			this.lblRange1b = new System.Windows.Forms.Label();
			this.lblRange1bplus = new System.Windows.Forms.Label();
			this.lblRange2b = new System.Windows.Forms.Label();
			this.lblRange3b = new System.Windows.Forms.Label();
			this.lblRangefo = new System.Windows.Forms.Label();
			this.lblRangegb = new System.Windows.Forms.Label();
			this.lblRangehr = new System.Windows.Forms.Label();
			this.lblRangepu = new System.Windows.Forms.Label();
			this.lblRangeso = new System.Windows.Forms.Label();
			this.lblRangew = new System.Windows.Forms.Label();
			this.lblStatic10 = new System.Windows.Forms.Label();
			this.lblStatic11 = new System.Windows.Forms.Label();
			this.lblStatic12 = new System.Windows.Forms.Label();
			this.lblStatic13 = new System.Windows.Forms.Label();
			this.lblStatic4 = new System.Windows.Forms.Label();
			this.lblStatic5 = new System.Windows.Forms.Label();
			this.lblStatic6 = new System.Windows.Forms.Label();
			this.lblStatic7 = new System.Windows.Forms.Label();
			this.lblStatic8 = new System.Windows.Forms.Label();
			this.lblStatic9 = new System.Windows.Forms.Label();
			this.grpStatic14 = new System.Windows.Forms.GroupBox();
			this.lbl2bgame = new System.Windows.Forms.Label();
			this.lbl2bseason = new System.Windows.Forms.Label();
			this.lbl3bgame = new System.Windows.Forms.Label();
			this.lbl3bseason = new System.Windows.Forms.Label();
			this.lblAbgame = new System.Windows.Forms.Label();
			this.lblAbseason = new System.Windows.Forms.Label();
			this.lblAvggame = new System.Windows.Forms.Label();
			this.lblAvgseason = new System.Windows.Forms.Label();
			this.lblBbgame = new System.Windows.Forms.Label();
			this.lblBbseason = new System.Windows.Forms.Label();
			this.lblHgame = new System.Windows.Forms.Label();
			this.lblHrgame = new System.Windows.Forms.Label();
			this.lblHrseason = new System.Windows.Forms.Label();
			this.lblHseason = new System.Windows.Forms.Label();
			this.lblKgame = new System.Windows.Forms.Label();
			this.lblRseason = new System.Windows.Forms.Label();
			this.lblStatic25 = new System.Windows.Forms.Label();
			this.lblKseason = new System.Windows.Forms.Label();
			this.lblRgame = new System.Windows.Forms.Label();
			this.lblObpgame = new System.Windows.Forms.Label();
			this.lblObpseason = new System.Windows.Forms.Label();
			this.lblRbigame = new System.Windows.Forms.Label();
			this.lblRbiseason = new System.Windows.Forms.Label();
			this.lblSacgame = new System.Windows.Forms.Label();
			this.lblSacseason = new System.Windows.Forms.Label();
			this.lblSbgame = new System.Windows.Forms.Label();
			this.lblSbseason = new System.Windows.Forms.Label();
			this.lblSluggame = new System.Windows.Forms.Label();
			this.lblSlugseason = new System.Windows.Forms.Label();
			this.lblStatic15 = new System.Windows.Forms.Label();
			this.lblStatic16 = new System.Windows.Forms.Label();
			this.lblStatic20 = new System.Windows.Forms.Label();
			this.lblStatic21 = new System.Windows.Forms.Label();
			this.lblStatic22 = new System.Windows.Forms.Label();
			this.lblStatic23 = new System.Windows.Forms.Label();
			this.lblStatic24 = new System.Windows.Forms.Label();
			this.lblStatic26 = new System.Windows.Forms.Label();
			this.lblStatic27 = new System.Windows.Forms.Label();
			this.lblStatic28 = new System.Windows.Forms.Label();
			this.lblStatic29 = new System.Windows.Forms.Label();
			this.lblStatic30 = new System.Windows.Forms.Label();
			this.lblStatic31 = new System.Windows.Forms.Label();
			this.lblStatic32 = new System.Windows.Forms.Label();
			this.lblStatic33 = new System.Windows.Forms.Label();
			this.lblStatic17 = new System.Windows.Forms.Label();
			this.lblName = new System.Windows.Forms.Label();
			this.lblStatic18 = new System.Windows.Forms.Label();
			this.lblStatic19 = new System.Windows.Forms.Label();
			this.lblSpeed = new System.Windows.Forms.Label();
			this.lblOnbase = new System.Windows.Forms.Label();
			this.lblBats = new System.Windows.Forms.Label();
			this.grpStatic3.SuspendLayout();
			this.grpStatic14.SuspendLayout();
			this.SuspendLayout();
			// 
			// btnIdok
			// 
			this.btnIdok.DialogResult = System.Windows.Forms.DialogResult.OK;
			this.btnIdok.Location = new System.Drawing.Point(448, 34);
			this.btnIdok.Name = "btnIdok";
			this.btnIdok.Size = new System.Drawing.Size(75, 24);
			this.btnIdok.TabIndex = 1;
			this.btnIdok.Text = "&Close";
			// 
			// lblStatic1
			// 
			this.lblStatic1.AutoSize = true;
			this.lblStatic1.Location = new System.Drawing.Point(14, 48);
			this.lblStatic1.Name = "lblStatic1";
			this.lblStatic1.Size = new System.Drawing.Size(83, 13);
			this.lblStatic1.TabIndex = 2;
			this.lblStatic1.Text = "Position/Rating:";
			// 
			// lblPosition1
			// 
			this.lblPosition1.AutoSize = true;
			this.lblPosition1.Location = new System.Drawing.Point(122, 48);
			this.lblPosition1.Name = "lblPosition1";
			this.lblPosition1.Size = new System.Drawing.Size(34, 13);
			this.lblPosition1.TabIndex = 3;
			this.lblPosition1.Text = "Static";
			// 
			// lblPosition2
			// 
			this.lblPosition2.AutoSize = true;
			this.lblPosition2.Location = new System.Drawing.Point(122, 70);
			this.lblPosition2.Name = "lblPosition2";
			this.lblPosition2.Size = new System.Drawing.Size(34, 13);
			this.lblPosition2.TabIndex = 4;
			this.lblPosition2.Text = "Static";
			// 
			// lblStatic2
			// 
			this.lblStatic2.AutoSize = true;
			this.lblStatic2.Location = new System.Drawing.Point(14, 93);
			this.lblStatic2.Name = "lblStatic2";
			this.lblStatic2.Size = new System.Drawing.Size(36, 13);
			this.lblStatic2.TabIndex = 5;
			this.lblStatic2.Text = "Points";
			// 
			// lblPoints
			// 
			this.lblPoints.AutoSize = true;
			this.lblPoints.Location = new System.Drawing.Point(122, 93);
			this.lblPoints.Name = "lblPoints";
			this.lblPoints.Size = new System.Drawing.Size(34, 13);
			this.lblPoints.TabIndex = 6;
			this.lblPoints.Text = "Static";
			// 
			// grpStatic3
			// 
			this.grpStatic3.Controls.Add(this.lblRange1b);
			this.grpStatic3.Controls.Add(this.lblRange1bplus);
			this.grpStatic3.Controls.Add(this.lblRange2b);
			this.grpStatic3.Controls.Add(this.lblRange3b);
			this.grpStatic3.Controls.Add(this.lblRangefo);
			this.grpStatic3.Controls.Add(this.lblRangegb);
			this.grpStatic3.Controls.Add(this.lblRangehr);
			this.grpStatic3.Controls.Add(this.lblRangepu);
			this.grpStatic3.Controls.Add(this.lblRangeso);
			this.grpStatic3.Controls.Add(this.lblRangew);
			this.grpStatic3.Controls.Add(this.lblStatic10);
			this.grpStatic3.Controls.Add(this.lblStatic11);
			this.grpStatic3.Controls.Add(this.lblStatic12);
			this.grpStatic3.Controls.Add(this.lblStatic13);
			this.grpStatic3.Controls.Add(this.lblStatic4);
			this.grpStatic3.Controls.Add(this.lblStatic5);
			this.grpStatic3.Controls.Add(this.lblStatic6);
			this.grpStatic3.Controls.Add(this.lblStatic7);
			this.grpStatic3.Controls.Add(this.lblStatic8);
			this.grpStatic3.Controls.Add(this.lblStatic9);
			this.grpStatic3.Location = new System.Drawing.Point(266, 27);
			this.grpStatic3.Name = "grpStatic3";
			this.grpStatic3.Size = new System.Drawing.Size(132, 208);
			this.grpStatic3.TabIndex = 7;
			this.grpStatic3.TabStop = false;
			this.grpStatic3.Text = "Outcome";
			// 
			// lblRange1b
			// 
			this.lblRange1b.Location = new System.Drawing.Point(14, 106);
			this.lblRange1b.Name = "lblRange1b";
			this.lblRange1b.Size = new System.Drawing.Size(40, 14);
			this.lblRange1b.TabIndex = 61;
			this.lblRange1b.Text = "Static";
			this.lblRange1b.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRange1bplus
			// 
			this.lblRange1bplus.Location = new System.Drawing.Point(14, 122);
			this.lblRange1bplus.Name = "lblRange1bplus";
			this.lblRange1bplus.Size = new System.Drawing.Size(40, 14);
			this.lblRange1bplus.TabIndex = 62;
			this.lblRange1bplus.Text = "Static";
			this.lblRange1bplus.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRange2b
			// 
			this.lblRange2b.Location = new System.Drawing.Point(14, 138);
			this.lblRange2b.Name = "lblRange2b";
			this.lblRange2b.Size = new System.Drawing.Size(40, 14);
			this.lblRange2b.TabIndex = 63;
			this.lblRange2b.Text = "Static";
			this.lblRange2b.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRange3b
			// 
			this.lblRange3b.Location = new System.Drawing.Point(14, 154);
			this.lblRange3b.Name = "lblRange3b";
			this.lblRange3b.Size = new System.Drawing.Size(40, 14);
			this.lblRange3b.TabIndex = 64;
			this.lblRange3b.Text = "Static";
			this.lblRange3b.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangefo
			// 
			this.lblRangefo.Location = new System.Drawing.Point(14, 74);
			this.lblRangefo.Name = "lblRangefo";
			this.lblRangefo.Size = new System.Drawing.Size(40, 14);
			this.lblRangefo.TabIndex = 59;
			this.lblRangefo.Text = "Static";
			this.lblRangefo.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangegb
			// 
			this.lblRangegb.Location = new System.Drawing.Point(14, 58);
			this.lblRangegb.Name = "lblRangegb";
			this.lblRangegb.Size = new System.Drawing.Size(40, 14);
			this.lblRangegb.TabIndex = 58;
			this.lblRangegb.Text = "Static";
			this.lblRangegb.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangehr
			// 
			this.lblRangehr.Location = new System.Drawing.Point(14, 170);
			this.lblRangehr.Name = "lblRangehr";
			this.lblRangehr.Size = new System.Drawing.Size(40, 14);
			this.lblRangehr.TabIndex = 65;
			this.lblRangehr.Text = "Static";
			this.lblRangehr.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangepu
			// 
			this.lblRangepu.Location = new System.Drawing.Point(14, 26);
			this.lblRangepu.Name = "lblRangepu";
			this.lblRangepu.Size = new System.Drawing.Size(40, 14);
			this.lblRangepu.TabIndex = 56;
			this.lblRangepu.Text = "Static";
			this.lblRangepu.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangeso
			// 
			this.lblRangeso.Location = new System.Drawing.Point(14, 42);
			this.lblRangeso.Name = "lblRangeso";
			this.lblRangeso.Size = new System.Drawing.Size(40, 14);
			this.lblRangeso.TabIndex = 57;
			this.lblRangeso.Text = "Static";
			this.lblRangeso.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangew
			// 
			this.lblRangew.Location = new System.Drawing.Point(14, 90);
			this.lblRangew.Name = "lblRangew";
			this.lblRangew.Size = new System.Drawing.Size(40, 14);
			this.lblRangew.TabIndex = 60;
			this.lblRangew.Text = "Static";
			this.lblRangew.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblStatic10
			// 
			this.lblStatic10.AutoSize = true;
			this.lblStatic10.Location = new System.Drawing.Point(67, 122);
			this.lblStatic10.Name = "lblStatic10";
			this.lblStatic10.Size = new System.Drawing.Size(42, 13);
			this.lblStatic10.TabIndex = 14;
			this.lblStatic10.Text = "Single+";
			// 
			// lblStatic11
			// 
			this.lblStatic11.AutoSize = true;
			this.lblStatic11.Location = new System.Drawing.Point(67, 138);
			this.lblStatic11.Name = "lblStatic11";
			this.lblStatic11.Size = new System.Drawing.Size(41, 13);
			this.lblStatic11.TabIndex = 15;
			this.lblStatic11.Text = "Double";
			// 
			// lblStatic12
			// 
			this.lblStatic12.AutoSize = true;
			this.lblStatic12.Location = new System.Drawing.Point(67, 154);
			this.lblStatic12.Name = "lblStatic12";
			this.lblStatic12.Size = new System.Drawing.Size(33, 13);
			this.lblStatic12.TabIndex = 16;
			this.lblStatic12.Text = "Triple";
			// 
			// lblStatic13
			// 
			this.lblStatic13.AutoSize = true;
			this.lblStatic13.Location = new System.Drawing.Point(67, 170);
			this.lblStatic13.Name = "lblStatic13";
			this.lblStatic13.Size = new System.Drawing.Size(58, 13);
			this.lblStatic13.TabIndex = 17;
			this.lblStatic13.Text = "Home Run";
			// 
			// lblStatic4
			// 
			this.lblStatic4.AutoSize = true;
			this.lblStatic4.Location = new System.Drawing.Point(67, 26);
			this.lblStatic4.Name = "lblStatic4";
			this.lblStatic4.Size = new System.Drawing.Size(45, 13);
			this.lblStatic4.TabIndex = 8;
			this.lblStatic4.Text = "Out(PU)";
			// 
			// lblStatic5
			// 
			this.lblStatic5.AutoSize = true;
			this.lblStatic5.Location = new System.Drawing.Point(67, 42);
			this.lblStatic5.Name = "lblStatic5";
			this.lblStatic5.Size = new System.Drawing.Size(45, 13);
			this.lblStatic5.TabIndex = 9;
			this.lblStatic5.Text = "Out(SO)";
			// 
			// lblStatic6
			// 
			this.lblStatic6.AutoSize = true;
			this.lblStatic6.Location = new System.Drawing.Point(67, 58);
			this.lblStatic6.Name = "lblStatic6";
			this.lblStatic6.Size = new System.Drawing.Size(45, 13);
			this.lblStatic6.TabIndex = 10;
			this.lblStatic6.Text = "Out(GB)";
			// 
			// lblStatic7
			// 
			this.lblStatic7.AutoSize = true;
			this.lblStatic7.Location = new System.Drawing.Point(67, 74);
			this.lblStatic7.Name = "lblStatic7";
			this.lblStatic7.Size = new System.Drawing.Size(43, 13);
			this.lblStatic7.TabIndex = 11;
			this.lblStatic7.Text = "Out(FB)";
			// 
			// lblStatic8
			// 
			this.lblStatic8.AutoSize = true;
			this.lblStatic8.Location = new System.Drawing.Point(67, 90);
			this.lblStatic8.Name = "lblStatic8";
			this.lblStatic8.Size = new System.Drawing.Size(32, 13);
			this.lblStatic8.TabIndex = 12;
			this.lblStatic8.Text = "Walk";
			// 
			// lblStatic9
			// 
			this.lblStatic9.AutoSize = true;
			this.lblStatic9.Location = new System.Drawing.Point(67, 106);
			this.lblStatic9.Name = "lblStatic9";
			this.lblStatic9.Size = new System.Drawing.Size(36, 13);
			this.lblStatic9.TabIndex = 13;
			this.lblStatic9.Text = "Single";
			// 
			// grpStatic14
			// 
			this.grpStatic14.Controls.Add(this.lbl2bgame);
			this.grpStatic14.Controls.Add(this.lbl2bseason);
			this.grpStatic14.Controls.Add(this.lbl3bgame);
			this.grpStatic14.Controls.Add(this.lbl3bseason);
			this.grpStatic14.Controls.Add(this.lblAbgame);
			this.grpStatic14.Controls.Add(this.lblAbseason);
			this.grpStatic14.Controls.Add(this.lblAvggame);
			this.grpStatic14.Controls.Add(this.lblAvgseason);
			this.grpStatic14.Controls.Add(this.lblBbgame);
			this.grpStatic14.Controls.Add(this.lblBbseason);
			this.grpStatic14.Controls.Add(this.lblHgame);
			this.grpStatic14.Controls.Add(this.lblHrgame);
			this.grpStatic14.Controls.Add(this.lblHrseason);
			this.grpStatic14.Controls.Add(this.lblHseason);
			this.grpStatic14.Controls.Add(this.lblKgame);
			this.grpStatic14.Controls.Add(this.lblRseason);
			this.grpStatic14.Controls.Add(this.lblStatic25);
			this.grpStatic14.Controls.Add(this.lblKseason);
			this.grpStatic14.Controls.Add(this.lblRgame);
			this.grpStatic14.Controls.Add(this.lblObpgame);
			this.grpStatic14.Controls.Add(this.lblObpseason);
			this.grpStatic14.Controls.Add(this.lblRbigame);
			this.grpStatic14.Controls.Add(this.lblRbiseason);
			this.grpStatic14.Controls.Add(this.lblSacgame);
			this.grpStatic14.Controls.Add(this.lblSacseason);
			this.grpStatic14.Controls.Add(this.lblSbgame);
			this.grpStatic14.Controls.Add(this.lblSbseason);
			this.grpStatic14.Controls.Add(this.lblSluggame);
			this.grpStatic14.Controls.Add(this.lblSlugseason);
			this.grpStatic14.Controls.Add(this.lblStatic15);
			this.grpStatic14.Controls.Add(this.lblStatic16);
			this.grpStatic14.Controls.Add(this.lblStatic20);
			this.grpStatic14.Controls.Add(this.lblStatic21);
			this.grpStatic14.Controls.Add(this.lblStatic22);
			this.grpStatic14.Controls.Add(this.lblStatic23);
			this.grpStatic14.Controls.Add(this.lblStatic24);
			this.grpStatic14.Controls.Add(this.lblStatic26);
			this.grpStatic14.Controls.Add(this.lblStatic27);
			this.grpStatic14.Controls.Add(this.lblStatic28);
			this.grpStatic14.Controls.Add(this.lblStatic29);
			this.grpStatic14.Controls.Add(this.lblStatic30);
			this.grpStatic14.Controls.Add(this.lblStatic31);
			this.grpStatic14.Controls.Add(this.lblStatic32);
			this.grpStatic14.Controls.Add(this.lblStatic33);
			this.grpStatic14.Location = new System.Drawing.Point(14, 242);
			this.grpStatic14.Name = "grpStatic14";
			this.grpStatic14.Size = new System.Drawing.Size(531, 106);
			this.grpStatic14.TabIndex = 18;
			this.grpStatic14.TabStop = false;
			this.grpStatic14.Text = "Statistics";
			// 
			// lbl2bgame
			// 
			this.lbl2bgame.Location = new System.Drawing.Point(162, 70);
			this.lbl2bgame.Name = "lbl2bgame";
			this.lbl2bgame.Size = new System.Drawing.Size(23, 17);
			this.lbl2bgame.TabIndex = 68;
			this.lbl2bgame.Text = "888";
			this.lbl2bgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lbl2bseason
			// 
			this.lbl2bseason.Location = new System.Drawing.Point(162, 44);
			this.lbl2bseason.Name = "lbl2bseason";
			this.lbl2bseason.Size = new System.Drawing.Size(23, 17);
			this.lbl2bseason.TabIndex = 44;
			this.lbl2bseason.Text = "888";
			this.lbl2bseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lbl3bgame
			// 
			this.lbl3bgame.Location = new System.Drawing.Point(192, 70);
			this.lbl3bgame.Name = "lbl3bgame";
			this.lbl3bgame.Size = new System.Drawing.Size(23, 17);
			this.lbl3bgame.TabIndex = 69;
			this.lbl3bgame.Text = "3B";
			this.lbl3bgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lbl3bseason
			// 
			this.lbl3bseason.Location = new System.Drawing.Point(192, 44);
			this.lbl3bseason.Name = "lbl3bseason";
			this.lbl3bseason.Size = new System.Drawing.Size(23, 17);
			this.lbl3bseason.TabIndex = 45;
			this.lbl3bseason.Text = "3B";
			this.lbl3bseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblAbgame
			// 
			this.lblAbgame.Location = new System.Drawing.Point(78, 70);
			this.lblAbgame.Name = "lblAbgame";
			this.lblAbgame.Size = new System.Drawing.Size(23, 17);
			this.lblAbgame.TabIndex = 66;
			this.lblAbgame.Text = "888";
			this.lblAbgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblAbseason
			// 
			this.lblAbseason.Location = new System.Drawing.Point(66, 44);
			this.lblAbseason.Name = "lblAbseason";
			this.lblAbseason.Size = new System.Drawing.Size(35, 17);
			this.lblAbseason.TabIndex = 42;
			this.lblAbseason.Text = "888";
			this.lblAbseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblAvggame
			// 
			this.lblAvggame.Location = new System.Drawing.Point(391, 70);
			this.lblAvggame.Name = "lblAvggame";
			this.lblAvggame.Size = new System.Drawing.Size(40, 17);
			this.lblAvggame.TabIndex = 77;
			this.lblAvggame.Text = ".888";
			this.lblAvggame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblAvgseason
			// 
			this.lblAvgseason.Location = new System.Drawing.Point(391, 44);
			this.lblAvgseason.Name = "lblAvgseason";
			this.lblAvgseason.Size = new System.Drawing.Size(40, 17);
			this.lblAvgseason.TabIndex = 53;
			this.lblAvgseason.Text = ".888";
			this.lblAvgseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblBbgame
			// 
			this.lblBbgame.Location = new System.Drawing.Point(306, 70);
			this.lblBbgame.Name = "lblBbgame";
			this.lblBbgame.Size = new System.Drawing.Size(23, 17);
			this.lblBbgame.TabIndex = 76;
			this.lblBbgame.Text = "BB";
			this.lblBbgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblBbseason
			// 
			this.lblBbseason.Location = new System.Drawing.Point(306, 44);
			this.lblBbseason.Name = "lblBbseason";
			this.lblBbseason.Size = new System.Drawing.Size(23, 17);
			this.lblBbseason.TabIndex = 52;
			this.lblBbseason.Text = "BB";
			this.lblBbseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblHgame
			// 
			this.lblHgame.Location = new System.Drawing.Point(133, 70);
			this.lblHgame.Name = "lblHgame";
			this.lblHgame.Size = new System.Drawing.Size(23, 17);
			this.lblHgame.TabIndex = 67;
			this.lblHgame.Text = "H";
			this.lblHgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblHrgame
			// 
			this.lblHrgame.Location = new System.Drawing.Point(218, 70);
			this.lblHrgame.Name = "lblHrgame";
			this.lblHrgame.Size = new System.Drawing.Size(23, 17);
			this.lblHrgame.TabIndex = 70;
			this.lblHrgame.Text = "HR";
			this.lblHrgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblHrseason
			// 
			this.lblHrseason.Location = new System.Drawing.Point(218, 44);
			this.lblHrseason.Name = "lblHrseason";
			this.lblHrseason.Size = new System.Drawing.Size(23, 17);
			this.lblHrseason.TabIndex = 46;
			this.lblHrseason.Text = "HR";
			this.lblHrseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblHseason
			// 
			this.lblHseason.Location = new System.Drawing.Point(133, 44);
			this.lblHseason.Name = "lblHseason";
			this.lblHseason.Size = new System.Drawing.Size(23, 17);
			this.lblHseason.TabIndex = 43;
			this.lblHseason.Text = "H";
			this.lblHseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblKgame
			// 
			this.lblKgame.Location = new System.Drawing.Point(276, 70);
			this.lblKgame.Name = "lblKgame";
			this.lblKgame.Size = new System.Drawing.Size(23, 17);
			this.lblKgame.TabIndex = 75;
			this.lblKgame.Text = "K";
			this.lblKgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblRseason
			// 
			this.lblRseason.Location = new System.Drawing.Point(108, 44);
			this.lblRseason.Name = "lblRseason";
			this.lblRseason.Size = new System.Drawing.Size(23, 17);
			this.lblRseason.TabIndex = 47;
			this.lblRseason.Text = "R";
			this.lblRseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic25
			// 
			this.lblStatic25.Location = new System.Drawing.Point(108, 20);
			this.lblStatic25.Name = "lblStatic25";
			this.lblStatic25.Size = new System.Drawing.Size(23, 14);
			this.lblStatic25.TabIndex = 33;
			this.lblStatic25.Text = "R";
			this.lblStatic25.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblKseason
			// 
			this.lblKseason.Location = new System.Drawing.Point(276, 44);
			this.lblKseason.Name = "lblKseason";
			this.lblKseason.Size = new System.Drawing.Size(23, 17);
			this.lblKseason.TabIndex = 51;
			this.lblKseason.Text = "K";
			this.lblKseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblRgame
			// 
			this.lblRgame.Location = new System.Drawing.Point(108, 70);
			this.lblRgame.Name = "lblRgame";
			this.lblRgame.Size = new System.Drawing.Size(23, 17);
			this.lblRgame.TabIndex = 71;
			this.lblRgame.Text = "R";
			this.lblRgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblObpgame
			// 
			this.lblObpgame.Location = new System.Drawing.Point(433, 70);
			this.lblObpgame.Name = "lblObpgame";
			this.lblObpgame.Size = new System.Drawing.Size(42, 17);
			this.lblObpgame.TabIndex = 78;
			this.lblObpgame.Text = ".888";
			this.lblObpgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblObpseason
			// 
			this.lblObpseason.Location = new System.Drawing.Point(433, 44);
			this.lblObpseason.Name = "lblObpseason";
			this.lblObpseason.Size = new System.Drawing.Size(42, 17);
			this.lblObpseason.TabIndex = 54;
			this.lblObpseason.Text = ".888";
			this.lblObpseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblRbigame
			// 
			this.lblRbigame.Location = new System.Drawing.Point(248, 70);
			this.lblRbigame.Name = "lblRbigame";
			this.lblRbigame.Size = new System.Drawing.Size(23, 17);
			this.lblRbigame.TabIndex = 72;
			this.lblRbigame.Text = "RBI";
			this.lblRbigame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblRbiseason
			// 
			this.lblRbiseason.Location = new System.Drawing.Point(240, 44);
			this.lblRbiseason.Name = "lblRbiseason";
			this.lblRbiseason.Size = new System.Drawing.Size(31, 17);
			this.lblRbiseason.TabIndex = 48;
			this.lblRbiseason.Text = "RBI";
			this.lblRbiseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblSacgame
			// 
			this.lblSacgame.Location = new System.Drawing.Point(334, 70);
			this.lblSacgame.Name = "lblSacgame";
			this.lblSacgame.Size = new System.Drawing.Size(23, 17);
			this.lblSacgame.TabIndex = 73;
			this.lblSacgame.Text = "SF";
			this.lblSacgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblSacseason
			// 
			this.lblSacseason.Location = new System.Drawing.Point(334, 44);
			this.lblSacseason.Name = "lblSacseason";
			this.lblSacseason.Size = new System.Drawing.Size(23, 17);
			this.lblSacseason.TabIndex = 49;
			this.lblSacseason.Text = "SF";
			this.lblSacseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblSbgame
			// 
			this.lblSbgame.Location = new System.Drawing.Point(362, 70);
			this.lblSbgame.Name = "lblSbgame";
			this.lblSbgame.Size = new System.Drawing.Size(23, 17);
			this.lblSbgame.TabIndex = 74;
			this.lblSbgame.Text = "SB";
			this.lblSbgame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblSbseason
			// 
			this.lblSbseason.Location = new System.Drawing.Point(362, 44);
			this.lblSbseason.Name = "lblSbseason";
			this.lblSbseason.Size = new System.Drawing.Size(23, 17);
			this.lblSbseason.TabIndex = 50;
			this.lblSbseason.Text = "SB";
			this.lblSbseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblSluggame
			// 
			this.lblSluggame.Location = new System.Drawing.Point(475, 70);
			this.lblSluggame.Name = "lblSluggame";
			this.lblSluggame.Size = new System.Drawing.Size(40, 17);
			this.lblSluggame.TabIndex = 79;
			this.lblSluggame.Text = "8.888";
			this.lblSluggame.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblSlugseason
			// 
			this.lblSlugseason.Location = new System.Drawing.Point(475, 44);
			this.lblSlugseason.Name = "lblSlugseason";
			this.lblSlugseason.Size = new System.Drawing.Size(40, 17);
			this.lblSlugseason.TabIndex = 55;
			this.lblSlugseason.Text = "8.888";
			this.lblSlugseason.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic15
			// 
			this.lblStatic15.Location = new System.Drawing.Point(13, 44);
			this.lblStatic15.Name = "lblStatic15";
			this.lblStatic15.Size = new System.Drawing.Size(47, 17);
			this.lblStatic15.TabIndex = 19;
			this.lblStatic15.Text = "Season";
			this.lblStatic15.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblStatic16
			// 
			this.lblStatic16.Location = new System.Drawing.Point(20, 70);
			this.lblStatic16.Name = "lblStatic16";
			this.lblStatic16.Size = new System.Drawing.Size(40, 17);
			this.lblStatic16.TabIndex = 20;
			this.lblStatic16.Text = "Game";
			this.lblStatic16.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblStatic20
			// 
			this.lblStatic20.Location = new System.Drawing.Point(78, 20);
			this.lblStatic20.Name = "lblStatic20";
			this.lblStatic20.Size = new System.Drawing.Size(23, 14);
			this.lblStatic20.TabIndex = 28;
			this.lblStatic20.Text = "AB";
			this.lblStatic20.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic21
			// 
			this.lblStatic21.Location = new System.Drawing.Point(133, 20);
			this.lblStatic21.Name = "lblStatic21";
			this.lblStatic21.Size = new System.Drawing.Size(23, 14);
			this.lblStatic21.TabIndex = 29;
			this.lblStatic21.Text = "H";
			this.lblStatic21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic22
			// 
			this.lblStatic22.Location = new System.Drawing.Point(162, 20);
			this.lblStatic22.Name = "lblStatic22";
			this.lblStatic22.Size = new System.Drawing.Size(23, 14);
			this.lblStatic22.TabIndex = 30;
			this.lblStatic22.Text = "2B";
			this.lblStatic22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic23
			// 
			this.lblStatic23.Location = new System.Drawing.Point(192, 20);
			this.lblStatic23.Name = "lblStatic23";
			this.lblStatic23.Size = new System.Drawing.Size(23, 14);
			this.lblStatic23.TabIndex = 31;
			this.lblStatic23.Text = "3B";
			this.lblStatic23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic24
			// 
			this.lblStatic24.Location = new System.Drawing.Point(218, 20);
			this.lblStatic24.Name = "lblStatic24";
			this.lblStatic24.Size = new System.Drawing.Size(23, 14);
			this.lblStatic24.TabIndex = 32;
			this.lblStatic24.Text = "HR";
			this.lblStatic24.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic26
			// 
			this.lblStatic26.Location = new System.Drawing.Point(244, 20);
			this.lblStatic26.Name = "lblStatic26";
			this.lblStatic26.Size = new System.Drawing.Size(33, 14);
			this.lblStatic26.TabIndex = 34;
			this.lblStatic26.Text = "RBI";
			this.lblStatic26.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic27
			// 
			this.lblStatic27.Location = new System.Drawing.Point(334, 20);
			this.lblStatic27.Name = "lblStatic27";
			this.lblStatic27.Size = new System.Drawing.Size(28, 14);
			this.lblStatic27.TabIndex = 35;
			this.lblStatic27.Text = "Sac";
			this.lblStatic27.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic28
			// 
			this.lblStatic28.Location = new System.Drawing.Point(362, 20);
			this.lblStatic28.Name = "lblStatic28";
			this.lblStatic28.Size = new System.Drawing.Size(23, 14);
			this.lblStatic28.TabIndex = 36;
			this.lblStatic28.Text = "SB";
			this.lblStatic28.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic29
			// 
			this.lblStatic29.Location = new System.Drawing.Point(276, 20);
			this.lblStatic29.Name = "lblStatic29";
			this.lblStatic29.Size = new System.Drawing.Size(23, 14);
			this.lblStatic29.TabIndex = 37;
			this.lblStatic29.Text = "K";
			this.lblStatic29.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic30
			// 
			this.lblStatic30.Location = new System.Drawing.Point(306, 20);
			this.lblStatic30.Name = "lblStatic30";
			this.lblStatic30.Size = new System.Drawing.Size(23, 14);
			this.lblStatic30.TabIndex = 38;
			this.lblStatic30.Text = "BB";
			this.lblStatic30.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// lblStatic31
			// 
			this.lblStatic31.Location = new System.Drawing.Point(391, 20);
			this.lblStatic31.Name = "lblStatic31";
			this.lblStatic31.Size = new System.Drawing.Size(40, 14);
			this.lblStatic31.TabIndex = 39;
			this.lblStatic31.Text = "Avg";
			this.lblStatic31.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic32
			// 
			this.lblStatic32.Location = new System.Drawing.Point(433, 20);
			this.lblStatic32.Name = "lblStatic32";
			this.lblStatic32.Size = new System.Drawing.Size(42, 14);
			this.lblStatic32.TabIndex = 40;
			this.lblStatic32.Text = "OBP";
			this.lblStatic32.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic33
			// 
			this.lblStatic33.Location = new System.Drawing.Point(475, 20);
			this.lblStatic33.Name = "lblStatic33";
			this.lblStatic33.Size = new System.Drawing.Size(40, 14);
			this.lblStatic33.TabIndex = 41;
			this.lblStatic33.Text = "Slug";
			this.lblStatic33.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic17
			// 
			this.lblStatic17.AutoSize = true;
			this.lblStatic17.Location = new System.Drawing.Point(14, 115);
			this.lblStatic17.Name = "lblStatic17";
			this.lblStatic17.Size = new System.Drawing.Size(28, 13);
			this.lblStatic17.TabIndex = 21;
			this.lblStatic17.Text = "Bats";
			// 
			// lblName
			// 
			this.lblName.AutoSize = true;
			this.lblName.Location = new System.Drawing.Point(14, 27);
			this.lblName.Name = "lblName";
			this.lblName.Size = new System.Drawing.Size(34, 13);
			this.lblName.TabIndex = 22;
			this.lblName.Text = "Static";
			// 
			// lblStatic18
			// 
			this.lblStatic18.AutoSize = true;
			this.lblStatic18.Location = new System.Drawing.Point(14, 138);
			this.lblStatic18.Name = "lblStatic18";
			this.lblStatic18.Size = new System.Drawing.Size(48, 13);
			this.lblStatic18.TabIndex = 23;
			this.lblStatic18.Text = "On Base";
			// 
			// lblStatic19
			// 
			this.lblStatic19.AutoSize = true;
			this.lblStatic19.Location = new System.Drawing.Point(14, 160);
			this.lblStatic19.Name = "lblStatic19";
			this.lblStatic19.Size = new System.Drawing.Size(38, 13);
			this.lblStatic19.TabIndex = 24;
			this.lblStatic19.Text = "Speed";
			// 
			// lblSpeed
			// 
			this.lblSpeed.AutoSize = true;
			this.lblSpeed.Location = new System.Drawing.Point(122, 160);
			this.lblSpeed.Name = "lblSpeed";
			this.lblSpeed.Size = new System.Drawing.Size(34, 13);
			this.lblSpeed.TabIndex = 25;
			this.lblSpeed.Text = "Static";
			// 
			// lblOnbase
			// 
			this.lblOnbase.AutoSize = true;
			this.lblOnbase.Location = new System.Drawing.Point(122, 138);
			this.lblOnbase.Name = "lblOnbase";
			this.lblOnbase.Size = new System.Drawing.Size(34, 13);
			this.lblOnbase.TabIndex = 26;
			this.lblOnbase.Text = "Static";
			// 
			// lblBats
			// 
			this.lblBats.AutoSize = true;
			this.lblBats.Location = new System.Drawing.Point(122, 115);
			this.lblBats.Name = "lblBats";
			this.lblBats.Size = new System.Drawing.Size(34, 13);
			this.lblBats.TabIndex = 27;
			this.lblBats.Text = "Static";
			// 
			// ShowBatterForm
			// 
			this.AcceptButton = this.btnIdok;
			this.ClientSize = new System.Drawing.Size(557, 359);
			this.Controls.Add(this.btnIdok);
			this.Controls.Add(this.lblBats);
			this.Controls.Add(this.lblName);
			this.Controls.Add(this.lblOnbase);
			this.Controls.Add(this.lblPoints);
			this.Controls.Add(this.lblPosition1);
			this.Controls.Add(this.lblPosition2);
			this.Controls.Add(this.lblSpeed);
			this.Controls.Add(this.lblStatic1);
			this.Controls.Add(this.lblStatic17);
			this.Controls.Add(this.lblStatic18);
			this.Controls.Add(this.lblStatic19);
			this.Controls.Add(this.lblStatic2);
			this.Controls.Add(this.grpStatic14);
			this.Controls.Add(this.grpStatic3);
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "ShowBatterForm";
			this.Text = "Batter Profile";
			this.grpStatic3.ResumeLayout(false);
			this.grpStatic3.PerformLayout();
			this.grpStatic14.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();

        } 
		#endregion

	}
}
