//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace DS.Showdown.SharedForms
{
	/// <summary>
	/// Summary description for ShowPitcherForm.
	/// </summary>

	partial class ShowPitcherForm : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Button btnIdok;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.GroupBox grpStatic1;
        private System.Windows.Forms.Label lblStatic2;
        private System.Windows.Forms.Label lblStatic3;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.Label lblStatic5;
        private System.Windows.Forms.Label lblStatic6;
        private System.Windows.Forms.Label lblStatic7;
        private System.Windows.Forms.Label lblStatic8;
        private System.Windows.Forms.Label lblStatic9;
        private System.Windows.Forms.Label lblStatic10;
        private System.Windows.Forms.Label lblStatic11;
        private System.Windows.Forms.Label lblRangepu;
        private System.Windows.Forms.Label lblRangeso;
        private System.Windows.Forms.Label lblRangegb;
        private System.Windows.Forms.Label lblRangefo;
        private System.Windows.Forms.Label lblRangew;
        private System.Windows.Forms.Label lblRange1b;
        private System.Windows.Forms.Label lblRange1bplus;
        private System.Windows.Forms.Label lblRange2b;
        private System.Windows.Forms.Label lblRange3b;
        private System.Windows.Forms.Label lblRangehr;
        private System.Windows.Forms.GroupBox grpStatic12;
        private System.Windows.Forms.Label lblStatic13;
        private System.Windows.Forms.Label lblStatic14;
        private System.Windows.Forms.Label lblStatic15;
        private System.Windows.Forms.Label lblStatic16;
        private System.Windows.Forms.Label lblStatic17;
        private System.Windows.Forms.Label lblStatic18;
        private System.Windows.Forms.Label lblStatic19;
        private System.Windows.Forms.Label lblStatic20;
        private System.Windows.Forms.Label lblStatic21;
        private System.Windows.Forms.Label lblStatic22;
        private System.Windows.Forms.Label lblStatic23;
        private System.Windows.Forms.Label lblWseason;
        private System.Windows.Forms.Label lblLseason;
        private System.Windows.Forms.Label lblErseason;
        private System.Windows.Forms.Label lblRseason;
        private System.Windows.Forms.Label lblKseason;
        private System.Windows.Forms.Label lblSseason;
        private System.Windows.Forms.Label lblBbseason;
        private System.Windows.Forms.Label lblIpseason;
        private System.Windows.Forms.Label lblEraseason;
        private System.Windows.Forms.Label lblWgame;
        private System.Windows.Forms.Label lblLgame;
        private System.Windows.Forms.Label lblErgame;
        private System.Windows.Forms.Label lblRgame;
        private System.Windows.Forms.Label lblKgame;
        private System.Windows.Forms.Label lblSgame;
        private System.Windows.Forms.Label lblBbgame;
        private System.Windows.Forms.Label lblIpgame;
        private System.Windows.Forms.Label lblEragame;
        private System.Windows.Forms.Label lblStatic24;
        private System.Windows.Forms.Label lblType;
        private System.Windows.Forms.Label lblStatic25;
        private System.Windows.Forms.Label lblPoints;
        private System.Windows.Forms.Label lblStatic26;
        private System.Windows.Forms.Label lblStatic27;
        private System.Windows.Forms.Label lblStatic28;
        private System.Windows.Forms.Label lblIp;
        private System.Windows.Forms.Label lblControl;
        private System.Windows.Forms.Label lblThrows;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.btnIdok = new System.Windows.Forms.Button();
			this.lblName = new System.Windows.Forms.Label();
			this.grpStatic1 = new System.Windows.Forms.GroupBox();
			this.lblRange1b = new System.Windows.Forms.Label();
			this.lblRange1bplus = new System.Windows.Forms.Label();
			this.lblRange2b = new System.Windows.Forms.Label();
			this.lblRange3b = new System.Windows.Forms.Label();
			this.lblRangefo = new System.Windows.Forms.Label();
			this.lblRangegb = new System.Windows.Forms.Label();
			this.lblRangehr = new System.Windows.Forms.Label();
			this.lblRangepu = new System.Windows.Forms.Label();
			this.lblRangeso = new System.Windows.Forms.Label();
			this.lblRangew = new System.Windows.Forms.Label();
			this.lblStatic10 = new System.Windows.Forms.Label();
			this.lblStatic11 = new System.Windows.Forms.Label();
			this.lblStatic2 = new System.Windows.Forms.Label();
			this.lblStatic3 = new System.Windows.Forms.Label();
			this.lblStatic4 = new System.Windows.Forms.Label();
			this.lblStatic5 = new System.Windows.Forms.Label();
			this.lblStatic6 = new System.Windows.Forms.Label();
			this.lblStatic7 = new System.Windows.Forms.Label();
			this.lblStatic8 = new System.Windows.Forms.Label();
			this.lblStatic9 = new System.Windows.Forms.Label();
			this.grpStatic12 = new System.Windows.Forms.GroupBox();
			this.lblBbgame = new System.Windows.Forms.Label();
			this.lblBbseason = new System.Windows.Forms.Label();
			this.lblEragame = new System.Windows.Forms.Label();
			this.lblEraseason = new System.Windows.Forms.Label();
			this.lblErgame = new System.Windows.Forms.Label();
			this.lblErseason = new System.Windows.Forms.Label();
			this.lblIpgame = new System.Windows.Forms.Label();
			this.lblIpseason = new System.Windows.Forms.Label();
			this.lblKgame = new System.Windows.Forms.Label();
			this.lblKseason = new System.Windows.Forms.Label();
			this.lblLgame = new System.Windows.Forms.Label();
			this.lblLseason = new System.Windows.Forms.Label();
			this.lblRgame = new System.Windows.Forms.Label();
			this.lblRseason = new System.Windows.Forms.Label();
			this.lblSgame = new System.Windows.Forms.Label();
			this.lblSseason = new System.Windows.Forms.Label();
			this.lblStatic13 = new System.Windows.Forms.Label();
			this.lblStatic14 = new System.Windows.Forms.Label();
			this.lblStatic15 = new System.Windows.Forms.Label();
			this.lblStatic16 = new System.Windows.Forms.Label();
			this.lblStatic17 = new System.Windows.Forms.Label();
			this.lblStatic18 = new System.Windows.Forms.Label();
			this.lblStatic19 = new System.Windows.Forms.Label();
			this.lblStatic20 = new System.Windows.Forms.Label();
			this.lblStatic21 = new System.Windows.Forms.Label();
			this.lblStatic22 = new System.Windows.Forms.Label();
			this.lblStatic23 = new System.Windows.Forms.Label();
			this.lblWgame = new System.Windows.Forms.Label();
			this.lblWseason = new System.Windows.Forms.Label();
			this.lblStatic24 = new System.Windows.Forms.Label();
			this.lblType = new System.Windows.Forms.Label();
			this.lblStatic25 = new System.Windows.Forms.Label();
			this.lblPoints = new System.Windows.Forms.Label();
			this.lblStatic26 = new System.Windows.Forms.Label();
			this.lblStatic27 = new System.Windows.Forms.Label();
			this.lblStatic28 = new System.Windows.Forms.Label();
			this.lblIp = new System.Windows.Forms.Label();
			this.lblControl = new System.Windows.Forms.Label();
			this.lblThrows = new System.Windows.Forms.Label();
			this.grpStatic1.SuspendLayout();
			this.grpStatic12.SuspendLayout();
			this.SuspendLayout();
			// 
			// btnIdok
			// 
			this.btnIdok.DialogResult = System.Windows.Forms.DialogResult.OK;
			this.btnIdok.Location = new System.Drawing.Point(165, 374);
			this.btnIdok.Name = "btnIdok";
			this.btnIdok.Size = new System.Drawing.Size(75, 24);
			this.btnIdok.TabIndex = 1;
			this.btnIdok.Text = "OK";
			// 
			// lblName
			// 
			this.lblName.AutoSize = true;
			this.lblName.Location = new System.Drawing.Point(26, 45);
			this.lblName.Name = "lblName";
			this.lblName.Size = new System.Drawing.Size(34, 13);
			this.lblName.TabIndex = 2;
			this.lblName.Text = "Static";
			// 
			// grpStatic1
			// 
			this.grpStatic1.Controls.Add(this.lblRange1b);
			this.grpStatic1.Controls.Add(this.lblRange1bplus);
			this.grpStatic1.Controls.Add(this.lblRange2b);
			this.grpStatic1.Controls.Add(this.lblRange3b);
			this.grpStatic1.Controls.Add(this.lblRangefo);
			this.grpStatic1.Controls.Add(this.lblRangegb);
			this.grpStatic1.Controls.Add(this.lblRangehr);
			this.grpStatic1.Controls.Add(this.lblRangepu);
			this.grpStatic1.Controls.Add(this.lblRangeso);
			this.grpStatic1.Controls.Add(this.lblRangew);
			this.grpStatic1.Controls.Add(this.lblStatic10);
			this.grpStatic1.Controls.Add(this.lblStatic11);
			this.grpStatic1.Controls.Add(this.lblStatic2);
			this.grpStatic1.Controls.Add(this.lblStatic3);
			this.grpStatic1.Controls.Add(this.lblStatic4);
			this.grpStatic1.Controls.Add(this.lblStatic5);
			this.grpStatic1.Controls.Add(this.lblStatic6);
			this.grpStatic1.Controls.Add(this.lblStatic7);
			this.grpStatic1.Controls.Add(this.lblStatic8);
			this.grpStatic1.Controls.Add(this.lblStatic9);
			this.grpStatic1.Location = new System.Drawing.Point(250, 32);
			this.grpStatic1.Name = "grpStatic1";
			this.grpStatic1.Size = new System.Drawing.Size(135, 208);
			this.grpStatic1.TabIndex = 3;
			this.grpStatic1.TabStop = false;
			this.grpStatic1.Text = "Outcome";
			// 
			// lblRange1b
			// 
			this.lblRange1b.Location = new System.Drawing.Point(16, 106);
			this.lblRange1b.Name = "lblRange1b";
			this.lblRange1b.Size = new System.Drawing.Size(40, 14);
			this.lblRange1b.TabIndex = 19;
			this.lblRange1b.Text = "Static";
			this.lblRange1b.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRange1bplus
			// 
			this.lblRange1bplus.Location = new System.Drawing.Point(16, 122);
			this.lblRange1bplus.Name = "lblRange1bplus";
			this.lblRange1bplus.Size = new System.Drawing.Size(40, 14);
			this.lblRange1bplus.TabIndex = 20;
			this.lblRange1bplus.Text = "Static";
			this.lblRange1bplus.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRange2b
			// 
			this.lblRange2b.Location = new System.Drawing.Point(16, 138);
			this.lblRange2b.Name = "lblRange2b";
			this.lblRange2b.Size = new System.Drawing.Size(40, 14);
			this.lblRange2b.TabIndex = 21;
			this.lblRange2b.Text = "Static";
			this.lblRange2b.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRange3b
			// 
			this.lblRange3b.Location = new System.Drawing.Point(16, 154);
			this.lblRange3b.Name = "lblRange3b";
			this.lblRange3b.Size = new System.Drawing.Size(40, 14);
			this.lblRange3b.TabIndex = 22;
			this.lblRange3b.Text = "Static";
			this.lblRange3b.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangefo
			// 
			this.lblRangefo.Location = new System.Drawing.Point(16, 74);
			this.lblRangefo.Name = "lblRangefo";
			this.lblRangefo.Size = new System.Drawing.Size(40, 14);
			this.lblRangefo.TabIndex = 17;
			this.lblRangefo.Text = "Static";
			this.lblRangefo.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangegb
			// 
			this.lblRangegb.Location = new System.Drawing.Point(16, 58);
			this.lblRangegb.Name = "lblRangegb";
			this.lblRangegb.Size = new System.Drawing.Size(40, 14);
			this.lblRangegb.TabIndex = 16;
			this.lblRangegb.Text = "Static";
			this.lblRangegb.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangehr
			// 
			this.lblRangehr.Location = new System.Drawing.Point(16, 170);
			this.lblRangehr.Name = "lblRangehr";
			this.lblRangehr.Size = new System.Drawing.Size(40, 14);
			this.lblRangehr.TabIndex = 23;
			this.lblRangehr.Text = "Static";
			this.lblRangehr.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangepu
			// 
			this.lblRangepu.Location = new System.Drawing.Point(16, 26);
			this.lblRangepu.Name = "lblRangepu";
			this.lblRangepu.Size = new System.Drawing.Size(40, 14);
			this.lblRangepu.TabIndex = 14;
			this.lblRangepu.Text = "Static";
			this.lblRangepu.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangeso
			// 
			this.lblRangeso.Location = new System.Drawing.Point(16, 42);
			this.lblRangeso.Name = "lblRangeso";
			this.lblRangeso.Size = new System.Drawing.Size(40, 14);
			this.lblRangeso.TabIndex = 15;
			this.lblRangeso.Text = "Static";
			this.lblRangeso.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblRangew
			// 
			this.lblRangew.Location = new System.Drawing.Point(16, 90);
			this.lblRangew.Name = "lblRangew";
			this.lblRangew.Size = new System.Drawing.Size(40, 14);
			this.lblRangew.TabIndex = 18;
			this.lblRangew.Text = "Static";
			this.lblRangew.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblStatic10
			// 
			this.lblStatic10.AutoSize = true;
			this.lblStatic10.Location = new System.Drawing.Point(68, 154);
			this.lblStatic10.Name = "lblStatic10";
			this.lblStatic10.Size = new System.Drawing.Size(33, 13);
			this.lblStatic10.TabIndex = 12;
			this.lblStatic10.Text = "Triple";
			// 
			// lblStatic11
			// 
			this.lblStatic11.AutoSize = true;
			this.lblStatic11.Location = new System.Drawing.Point(68, 170);
			this.lblStatic11.Name = "lblStatic11";
			this.lblStatic11.Size = new System.Drawing.Size(58, 13);
			this.lblStatic11.TabIndex = 13;
			this.lblStatic11.Text = "Home Run";
			// 
			// lblStatic2
			// 
			this.lblStatic2.AutoSize = true;
			this.lblStatic2.Location = new System.Drawing.Point(68, 26);
			this.lblStatic2.Name = "lblStatic2";
			this.lblStatic2.Size = new System.Drawing.Size(45, 13);
			this.lblStatic2.TabIndex = 4;
			this.lblStatic2.Text = "Out(PU)";
			// 
			// lblStatic3
			// 
			this.lblStatic3.AutoSize = true;
			this.lblStatic3.Location = new System.Drawing.Point(68, 42);
			this.lblStatic3.Name = "lblStatic3";
			this.lblStatic3.Size = new System.Drawing.Size(45, 13);
			this.lblStatic3.TabIndex = 5;
			this.lblStatic3.Text = "Out(SO)";
			// 
			// lblStatic4
			// 
			this.lblStatic4.AutoSize = true;
			this.lblStatic4.Location = new System.Drawing.Point(68, 58);
			this.lblStatic4.Name = "lblStatic4";
			this.lblStatic4.Size = new System.Drawing.Size(45, 13);
			this.lblStatic4.TabIndex = 6;
			this.lblStatic4.Text = "Out(GB)";
			// 
			// lblStatic5
			// 
			this.lblStatic5.AutoSize = true;
			this.lblStatic5.Location = new System.Drawing.Point(68, 74);
			this.lblStatic5.Name = "lblStatic5";
			this.lblStatic5.Size = new System.Drawing.Size(43, 13);
			this.lblStatic5.TabIndex = 7;
			this.lblStatic5.Text = "Out(FB)";
			// 
			// lblStatic6
			// 
			this.lblStatic6.AutoSize = true;
			this.lblStatic6.Location = new System.Drawing.Point(68, 90);
			this.lblStatic6.Name = "lblStatic6";
			this.lblStatic6.Size = new System.Drawing.Size(32, 13);
			this.lblStatic6.TabIndex = 8;
			this.lblStatic6.Text = "Walk";
			// 
			// lblStatic7
			// 
			this.lblStatic7.AutoSize = true;
			this.lblStatic7.Location = new System.Drawing.Point(68, 106);
			this.lblStatic7.Name = "lblStatic7";
			this.lblStatic7.Size = new System.Drawing.Size(36, 13);
			this.lblStatic7.TabIndex = 9;
			this.lblStatic7.Text = "Single";
			// 
			// lblStatic8
			// 
			this.lblStatic8.AutoSize = true;
			this.lblStatic8.Location = new System.Drawing.Point(68, 122);
			this.lblStatic8.Name = "lblStatic8";
			this.lblStatic8.Size = new System.Drawing.Size(42, 13);
			this.lblStatic8.TabIndex = 10;
			this.lblStatic8.Text = "Single+";
			// 
			// lblStatic9
			// 
			this.lblStatic9.AutoSize = true;
			this.lblStatic9.Location = new System.Drawing.Point(68, 138);
			this.lblStatic9.Name = "lblStatic9";
			this.lblStatic9.Size = new System.Drawing.Size(41, 13);
			this.lblStatic9.TabIndex = 11;
			this.lblStatic9.Text = "Double";
			// 
			// grpStatic12
			// 
			this.grpStatic12.Controls.Add(this.lblBbgame);
			this.grpStatic12.Controls.Add(this.lblBbseason);
			this.grpStatic12.Controls.Add(this.lblEragame);
			this.grpStatic12.Controls.Add(this.lblEraseason);
			this.grpStatic12.Controls.Add(this.lblErgame);
			this.grpStatic12.Controls.Add(this.lblErseason);
			this.grpStatic12.Controls.Add(this.lblIpgame);
			this.grpStatic12.Controls.Add(this.lblIpseason);
			this.grpStatic12.Controls.Add(this.lblKgame);
			this.grpStatic12.Controls.Add(this.lblKseason);
			this.grpStatic12.Controls.Add(this.lblLgame);
			this.grpStatic12.Controls.Add(this.lblLseason);
			this.grpStatic12.Controls.Add(this.lblRgame);
			this.grpStatic12.Controls.Add(this.lblRseason);
			this.grpStatic12.Controls.Add(this.lblSgame);
			this.grpStatic12.Controls.Add(this.lblSseason);
			this.grpStatic12.Controls.Add(this.lblStatic13);
			this.grpStatic12.Controls.Add(this.lblStatic14);
			this.grpStatic12.Controls.Add(this.lblStatic15);
			this.grpStatic12.Controls.Add(this.lblStatic16);
			this.grpStatic12.Controls.Add(this.lblStatic17);
			this.grpStatic12.Controls.Add(this.lblStatic18);
			this.grpStatic12.Controls.Add(this.lblStatic19);
			this.grpStatic12.Controls.Add(this.lblStatic20);
			this.grpStatic12.Controls.Add(this.lblStatic21);
			this.grpStatic12.Controls.Add(this.lblStatic22);
			this.grpStatic12.Controls.Add(this.lblStatic23);
			this.grpStatic12.Controls.Add(this.lblWgame);
			this.grpStatic12.Controls.Add(this.lblWseason);
			this.grpStatic12.Location = new System.Drawing.Point(20, 254);
			this.grpStatic12.Name = "grpStatic12";
			this.grpStatic12.Size = new System.Drawing.Size(440, 106);
			this.grpStatic12.TabIndex = 24;
			this.grpStatic12.TabStop = false;
			this.grpStatic12.Text = "Statistics";
			// 
			// lblBbgame
			// 
			this.lblBbgame.Location = new System.Drawing.Point(240, 72);
			this.lblBbgame.Name = "lblBbgame";
			this.lblBbgame.Size = new System.Drawing.Size(21, 17);
			this.lblBbgame.TabIndex = 51;
			this.lblBbgame.Text = "RBI";
			this.lblBbgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblBbseason
			// 
			this.lblBbseason.Location = new System.Drawing.Point(240, 47);
			this.lblBbseason.Name = "lblBbseason";
			this.lblBbseason.Size = new System.Drawing.Size(21, 17);
			this.lblBbseason.TabIndex = 42;
			this.lblBbseason.Text = "RBI";
			this.lblBbseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblEragame
			// 
			this.lblEragame.Location = new System.Drawing.Point(313, 72);
			this.lblEragame.Name = "lblEragame";
			this.lblEragame.Size = new System.Drawing.Size(39, 17);
			this.lblEragame.TabIndex = 53;
			this.lblEragame.Text = ".888";
			this.lblEragame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblEraseason
			// 
			this.lblEraseason.Location = new System.Drawing.Point(313, 47);
			this.lblEraseason.Name = "lblEraseason";
			this.lblEraseason.Size = new System.Drawing.Size(38, 17);
			this.lblEraseason.TabIndex = 44;
			this.lblEraseason.Text = ".888";
			this.lblEraseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblErgame
			// 
			this.lblErgame.Location = new System.Drawing.Point(154, 72);
			this.lblErgame.Name = "lblErgame";
			this.lblErgame.Size = new System.Drawing.Size(21, 17);
			this.lblErgame.TabIndex = 47;
			this.lblErgame.Text = "888";
			this.lblErgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblErseason
			// 
			this.lblErseason.Location = new System.Drawing.Point(154, 47);
			this.lblErseason.Name = "lblErseason";
			this.lblErseason.Size = new System.Drawing.Size(21, 17);
			this.lblErseason.TabIndex = 38;
			this.lblErseason.Text = "888";
			this.lblErseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblIpgame
			// 
			this.lblIpgame.Location = new System.Drawing.Point(268, 72);
			this.lblIpgame.Name = "lblIpgame";
			this.lblIpgame.Size = new System.Drawing.Size(36, 17);
			this.lblIpgame.TabIndex = 52;
			this.lblIpgame.Text = "K";
			this.lblIpgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblIpseason
			// 
			this.lblIpseason.Location = new System.Drawing.Point(268, 47);
			this.lblIpseason.Name = "lblIpseason";
			this.lblIpseason.Size = new System.Drawing.Size(36, 17);
			this.lblIpseason.TabIndex = 43;
			this.lblIpseason.Text = "K";
			this.lblIpseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblKgame
			// 
			this.lblKgame.Location = new System.Drawing.Point(211, 72);
			this.lblKgame.Name = "lblKgame";
			this.lblKgame.Size = new System.Drawing.Size(21, 17);
			this.lblKgame.TabIndex = 49;
			this.lblKgame.Text = "HR";
			this.lblKgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblKseason
			// 
			this.lblKseason.Location = new System.Drawing.Point(211, 47);
			this.lblKseason.Name = "lblKseason";
			this.lblKseason.Size = new System.Drawing.Size(21, 17);
			this.lblKseason.TabIndex = 40;
			this.lblKseason.Text = "HR";
			this.lblKseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblLgame
			// 
			this.lblLgame.Location = new System.Drawing.Point(96, 72);
			this.lblLgame.Name = "lblLgame";
			this.lblLgame.Size = new System.Drawing.Size(21, 17);
			this.lblLgame.TabIndex = 46;
			this.lblLgame.Text = "H";
			this.lblLgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblLseason
			// 
			this.lblLseason.Location = new System.Drawing.Point(97, 47);
			this.lblLseason.Name = "lblLseason";
			this.lblLseason.Size = new System.Drawing.Size(21, 17);
			this.lblLseason.TabIndex = 37;
			this.lblLseason.Text = "H";
			this.lblLseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblRgame
			// 
			this.lblRgame.Location = new System.Drawing.Point(182, 72);
			this.lblRgame.Name = "lblRgame";
			this.lblRgame.Size = new System.Drawing.Size(21, 17);
			this.lblRgame.TabIndex = 48;
			this.lblRgame.Text = "3B";
			this.lblRgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblRseason
			// 
			this.lblRseason.Location = new System.Drawing.Point(182, 47);
			this.lblRseason.Name = "lblRseason";
			this.lblRseason.Size = new System.Drawing.Size(21, 17);
			this.lblRseason.TabIndex = 39;
			this.lblRseason.Text = "3B";
			this.lblRseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblSgame
			// 
			this.lblSgame.Location = new System.Drawing.Point(126, 72);
			this.lblSgame.Name = "lblSgame";
			this.lblSgame.Size = new System.Drawing.Size(21, 17);
			this.lblSgame.TabIndex = 50;
			this.lblSgame.Text = "R";
			this.lblSgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblSseason
			// 
			this.lblSseason.Location = new System.Drawing.Point(126, 47);
			this.lblSseason.Name = "lblSseason";
			this.lblSseason.Size = new System.Drawing.Size(21, 17);
			this.lblSseason.TabIndex = 41;
			this.lblSseason.Text = "R";
			this.lblSseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblStatic13
			// 
			this.lblStatic13.Location = new System.Drawing.Point(13, 47);
			this.lblStatic13.Name = "lblStatic13";
			this.lblStatic13.Size = new System.Drawing.Size(49, 17);
			this.lblStatic13.TabIndex = 25;
			this.lblStatic13.Text = "Season";
			this.lblStatic13.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblStatic14
			// 
			this.lblStatic14.Location = new System.Drawing.Point(20, 72);
			this.lblStatic14.Name = "lblStatic14";
			this.lblStatic14.Size = new System.Drawing.Size(42, 17);
			this.lblStatic14.TabIndex = 26;
			this.lblStatic14.Text = "Game";
			this.lblStatic14.TextAlign = System.Drawing.ContentAlignment.TopRight;
			// 
			// lblStatic15
			// 
			this.lblStatic15.Location = new System.Drawing.Point(68, 23);
			this.lblStatic15.Name = "lblStatic15";
			this.lblStatic15.Size = new System.Drawing.Size(21, 14);
			this.lblStatic15.TabIndex = 27;
			this.lblStatic15.Text = "W";
			this.lblStatic15.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic16
			// 
			this.lblStatic16.Location = new System.Drawing.Point(97, 23);
			this.lblStatic16.Name = "lblStatic16";
			this.lblStatic16.Size = new System.Drawing.Size(21, 14);
			this.lblStatic16.TabIndex = 28;
			this.lblStatic16.Text = "L";
			this.lblStatic16.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic17
			// 
			this.lblStatic17.Location = new System.Drawing.Point(154, 23);
			this.lblStatic17.Name = "lblStatic17";
			this.lblStatic17.Size = new System.Drawing.Size(21, 14);
			this.lblStatic17.TabIndex = 29;
			this.lblStatic17.Text = "ER";
			this.lblStatic17.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic18
			// 
			this.lblStatic18.Location = new System.Drawing.Point(182, 23);
			this.lblStatic18.Name = "lblStatic18";
			this.lblStatic18.Size = new System.Drawing.Size(21, 14);
			this.lblStatic18.TabIndex = 30;
			this.lblStatic18.Text = "R";
			this.lblStatic18.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic19
			// 
			this.lblStatic19.Location = new System.Drawing.Point(211, 23);
			this.lblStatic19.Name = "lblStatic19";
			this.lblStatic19.Size = new System.Drawing.Size(21, 14);
			this.lblStatic19.TabIndex = 31;
			this.lblStatic19.Text = "K";
			this.lblStatic19.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic20
			// 
			this.lblStatic20.Location = new System.Drawing.Point(126, 23);
			this.lblStatic20.Name = "lblStatic20";
			this.lblStatic20.Size = new System.Drawing.Size(21, 14);
			this.lblStatic20.TabIndex = 32;
			this.lblStatic20.Text = "S";
			this.lblStatic20.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic21
			// 
			this.lblStatic21.Location = new System.Drawing.Point(240, 23);
			this.lblStatic21.Name = "lblStatic21";
			this.lblStatic21.Size = new System.Drawing.Size(21, 14);
			this.lblStatic21.TabIndex = 33;
			this.lblStatic21.Text = "BB";
			this.lblStatic21.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic22
			// 
			this.lblStatic22.Location = new System.Drawing.Point(276, 23);
			this.lblStatic22.Name = "lblStatic22";
			this.lblStatic22.Size = new System.Drawing.Size(21, 14);
			this.lblStatic22.TabIndex = 34;
			this.lblStatic22.Text = "IP";
			this.lblStatic22.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblStatic23
			// 
			this.lblStatic23.Location = new System.Drawing.Point(316, 23);
			this.lblStatic23.Name = "lblStatic23";
			this.lblStatic23.Size = new System.Drawing.Size(30, 14);
			this.lblStatic23.TabIndex = 35;
			this.lblStatic23.Text = "ERA";
			this.lblStatic23.TextAlign = System.Drawing.ContentAlignment.TopCenter;
			// 
			// lblWgame
			// 
			this.lblWgame.Location = new System.Drawing.Point(68, 72);
			this.lblWgame.Name = "lblWgame";
			this.lblWgame.Size = new System.Drawing.Size(21, 17);
			this.lblWgame.TabIndex = 45;
			this.lblWgame.Text = "888";
			this.lblWgame.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblWseason
			// 
			this.lblWseason.Location = new System.Drawing.Point(68, 47);
			this.lblWseason.Name = "lblWseason";
			this.lblWseason.Size = new System.Drawing.Size(21, 17);
			this.lblWseason.TabIndex = 36;
			this.lblWseason.Text = "888";
			this.lblWseason.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// lblStatic24
			// 
			this.lblStatic24.AutoSize = true;
			this.lblStatic24.Location = new System.Drawing.Point(26, 80);
			this.lblStatic24.Name = "lblStatic24";
			this.lblStatic24.Size = new System.Drawing.Size(31, 13);
			this.lblStatic24.TabIndex = 54;
			this.lblStatic24.Text = "Type";
			// 
			// lblType
			// 
			this.lblType.AutoSize = true;
			this.lblType.Location = new System.Drawing.Point(122, 80);
			this.lblType.Name = "lblType";
			this.lblType.Size = new System.Drawing.Size(34, 13);
			this.lblType.TabIndex = 55;
			this.lblType.Text = "Static";
			// 
			// lblStatic25
			// 
			this.lblStatic25.AutoSize = true;
			this.lblStatic25.Location = new System.Drawing.Point(26, 170);
			this.lblStatic25.Name = "lblStatic25";
			this.lblStatic25.Size = new System.Drawing.Size(36, 13);
			this.lblStatic25.TabIndex = 56;
			this.lblStatic25.Text = "Points";
			// 
			// lblPoints
			// 
			this.lblPoints.AutoSize = true;
			this.lblPoints.Location = new System.Drawing.Point(122, 170);
			this.lblPoints.Name = "lblPoints";
			this.lblPoints.Size = new System.Drawing.Size(34, 13);
			this.lblPoints.TabIndex = 57;
			this.lblPoints.Text = "Static";
			// 
			// lblStatic26
			// 
			this.lblStatic26.AutoSize = true;
			this.lblStatic26.Location = new System.Drawing.Point(26, 102);
			this.lblStatic26.Name = "lblStatic26";
			this.lblStatic26.Size = new System.Drawing.Size(42, 13);
			this.lblStatic26.TabIndex = 58;
			this.lblStatic26.Text = "Throws";
			// 
			// lblStatic27
			// 
			this.lblStatic27.AutoSize = true;
			this.lblStatic27.Location = new System.Drawing.Point(26, 125);
			this.lblStatic27.Name = "lblStatic27";
			this.lblStatic27.Size = new System.Drawing.Size(40, 13);
			this.lblStatic27.TabIndex = 59;
			this.lblStatic27.Text = "Control";
			// 
			// lblStatic28
			// 
			this.lblStatic28.AutoSize = true;
			this.lblStatic28.Location = new System.Drawing.Point(26, 147);
			this.lblStatic28.Name = "lblStatic28";
			this.lblStatic28.Size = new System.Drawing.Size(17, 13);
			this.lblStatic28.TabIndex = 60;
			this.lblStatic28.Text = "IP";
			// 
			// lblIp
			// 
			this.lblIp.AutoSize = true;
			this.lblIp.Location = new System.Drawing.Point(122, 147);
			this.lblIp.Name = "lblIp";
			this.lblIp.Size = new System.Drawing.Size(34, 13);
			this.lblIp.TabIndex = 61;
			this.lblIp.Text = "Static";
			// 
			// lblControl
			// 
			this.lblControl.AutoSize = true;
			this.lblControl.Location = new System.Drawing.Point(122, 125);
			this.lblControl.Name = "lblControl";
			this.lblControl.Size = new System.Drawing.Size(34, 13);
			this.lblControl.TabIndex = 62;
			this.lblControl.Text = "Static";
			// 
			// lblThrows
			// 
			this.lblThrows.AutoSize = true;
			this.lblThrows.Location = new System.Drawing.Point(122, 102);
			this.lblThrows.Name = "lblThrows";
			this.lblThrows.Size = new System.Drawing.Size(34, 13);
			this.lblThrows.TabIndex = 63;
			this.lblThrows.Text = "Static";
			// 
			// ShowPitcherForm
			// 
			this.AcceptButton = this.btnIdok;
			this.ClientSize = new System.Drawing.Size(506, 420);
			this.Controls.Add(this.btnIdok);
			this.Controls.Add(this.lblControl);
			this.Controls.Add(this.lblIp);
			this.Controls.Add(this.lblName);
			this.Controls.Add(this.lblPoints);
			this.Controls.Add(this.lblStatic24);
			this.Controls.Add(this.lblStatic25);
			this.Controls.Add(this.lblStatic26);
			this.Controls.Add(this.lblStatic27);
			this.Controls.Add(this.lblStatic28);
			this.Controls.Add(this.lblThrows);
			this.Controls.Add(this.lblType);
			this.Controls.Add(this.grpStatic1);
			this.Controls.Add(this.grpStatic12);
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "ShowPitcherForm";
			this.Text = "Pitcher Profile";
			this.grpStatic1.ResumeLayout(false);
			this.grpStatic1.PerformLayout();
			this.grpStatic12.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();

        } 
		#endregion

	}
}
