//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace DS.Showdown.Game
{
	/// <summary>
	/// Summary description for frmShowdownForm.
	/// </summary>

	partial class ShowdownForm : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Label lblHome1;
        private System.Windows.Forms.Label lblHome2;
        private System.Windows.Forms.Label lblHome3;
        private System.Windows.Forms.Label lblHome4;
        private System.Windows.Forms.Label lblHome5;
        private System.Windows.Forms.Label lblHome6;
        private System.Windows.Forms.Label lblHome7;
        private System.Windows.Forms.Label lblHome8;
        private System.Windows.Forms.Label lblHome9;
        private System.Windows.Forms.Label lblVisitor1;
        private System.Windows.Forms.Label lblVisitor2;
        private System.Windows.Forms.Label lblVisitor3;
        private System.Windows.Forms.Label lblVisitor4;
        private System.Windows.Forms.Label lblVisitor5;
        private System.Windows.Forms.Label lblVisitor6;
        private System.Windows.Forms.Label lblVisitor7;
        private System.Windows.Forms.Label lblVisitor8;
        private System.Windows.Forms.Label lblVisitor9;
        private System.Windows.Forms.Label lblAtbat;
        private System.Windows.Forms.Label lblOnfirst;
        private System.Windows.Forms.Label lblOnsecond;
        private System.Windows.Forms.Label lblOnthird;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.Label lblOuts;
        private System.Windows.Forms.GroupBox grpHomelineup;
        private System.Windows.Forms.GroupBox grpVislineup;
        private System.Windows.Forms.GroupBox grpStatic2;
        private System.Windows.Forms.Label lblVisruns;
        private System.Windows.Forms.Label lblVishits;
        private System.Windows.Forms.Label lblViserrors;
        private System.Windows.Forms.Label lblHomeruns;
        private System.Windows.Forms.Label lblHomehits;
        private System.Windows.Forms.Label lblHomeerrors;
        private System.Windows.Forms.Label lblStatic3;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.Label lblStatic5;
        private System.Windows.Forms.Label lblVisitname;
        private System.Windows.Forms.Label lblHomename;
        private System.Windows.Forms.Label lblStatic6;
        private System.Windows.Forms.Label lblStatic7;
        private System.Windows.Forms.Label lblStatic8;
        private System.Windows.Forms.Label lblStatic9;
        private System.Windows.Forms.Label lblHomepitcher;
        private System.Windows.Forms.Label lblVispitcher;
        private System.Windows.Forms.Label lblResult;
        private System.Windows.Forms.Button btnNextatbat;
        private System.Windows.Forms.Label lblVisitatbat;
        private System.Windows.Forms.Label lblHomeatbat;
        private System.Windows.Forms.Label lblStatic10;
        private System.Windows.Forms.Label lblInning;
        private System.Windows.Forms.Label lblInning1;
        private System.Windows.Forms.Label lblInning2;
        private System.Windows.Forms.Label lblInning3;
        private System.Windows.Forms.Label lblInning4;
        private System.Windows.Forms.Label lblInning5;
        private System.Windows.Forms.Label lblInning6;
        private System.Windows.Forms.Label lblInning7;
        private System.Windows.Forms.Label lblInning8;
        private System.Windows.Forms.Label lblInning9;
        private System.Windows.Forms.Label lblInning10;
        private System.Windows.Forms.Label lblVisinning1;
        private System.Windows.Forms.Label lblVisinning2;
        private System.Windows.Forms.Label lblVisinning3;
        private System.Windows.Forms.Label lblVisinning4;
        private System.Windows.Forms.Label lblVisinning5;
        private System.Windows.Forms.Label lblVisinning6;
        private System.Windows.Forms.Label lblVisinning7;
        private System.Windows.Forms.Label lblVisinning8;
        private System.Windows.Forms.Label lblVisinning9;
        private System.Windows.Forms.Label lblVisinning10;
        private System.Windows.Forms.Label lblHomeinning1;
        private System.Windows.Forms.Label lblHomeinning2;
        private System.Windows.Forms.Label lblHomeinning3;
        private System.Windows.Forms.Label lblHomeinning4;
        private System.Windows.Forms.Label lblHomeinning5;
        private System.Windows.Forms.Label lblHomeinning6;
        private System.Windows.Forms.Label lblHomeinning7;
        private System.Windows.Forms.Label lblHomeinning8;
        private System.Windows.Forms.Label lblHomeinning9;
        private System.Windows.Forms.Label lblHomeinning10;
        private System.Windows.Forms.PictureBox picStatic11;

		private System.Windows.Forms.MenuStrip mnuMainframe;
		private System.Windows.Forms.ToolStripMenuItem mnuFile;
		private System.Windows.Forms.ToolStripMenuItem mnuFileNew;
		private System.Windows.Forms.ToolStripMenuItem mnuFileOpen;
		private System.Windows.Forms.ToolStripMenuItem mnuFileSave;
		private System.Windows.Forms.ToolStripMenuItem mnuFileSaveAs;
		private System.Windows.Forms.ToolStripSeparator mnuSeparator;
		private System.Windows.Forms.ToolStripMenuItem mnuAppExit;
		private System.Windows.Forms.ToolStripMenuItem mnuEdit;
		private System.Windows.Forms.ToolStripMenuItem mnuEditUndo;
		private System.Windows.Forms.ToolStripSeparator mnuSeparator1;
		private System.Windows.Forms.ToolStripMenuItem mnuEditCut;
		private System.Windows.Forms.ToolStripMenuItem mnuEditCopy;
		private System.Windows.Forms.ToolStripMenuItem mnuEditPaste;
		private System.Windows.Forms.ToolStripSeparator mnuSeparator2;
		private System.Windows.Forms.ToolStripMenuItem mnuView;
		private System.Windows.Forms.ToolStripMenuItem mnuViewToolbar;
		private System.Windows.Forms.ToolStripMenuItem mnuViewStatusBar;
		private System.Windows.Forms.ToolStripSeparator mnuSeparator3;
		private System.Windows.Forms.ToolStripMenuItem mnuViewDoatbat;
		private System.Windows.Forms.ToolStripMenuItem mnuViewPlayLog;
		private System.Windows.Forms.ToolStripMenuItem mnuViewBoxscore;
		private System.Windows.Forms.ToolStripMenuItem mnuViewGamestats;
		private System.Windows.Forms.ToolStripMenuItem mnuViewSeasonstats;
		private System.Windows.Forms.ToolStripMenuItem mnuTeams;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamsEdit;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamsCreate;
		private System.Windows.Forms.ToolStripMenuItem mnuVisiting;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamvSelect;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamvLineup;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamvStats;
		private System.Windows.Forms.ToolStripMenuItem viewHomeTeamMenuItem;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamhSelect;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamhLineup;
		private System.Windows.Forms.ToolStripMenuItem mnuTeamhStats;
		private System.Windows.Forms.ToolStripMenuItem mnuGame;
		private System.Windows.Forms.ToolStripMenuItem mnuGamePlayball;
		private System.Windows.Forms.ToolStripMenuItem mnuHelp;
		private System.Windows.Forms.ToolStripMenuItem mnuAppAbout;




		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ShowdownForm));
            this.lblHome1 = new System.Windows.Forms.Label();
            this.lblHome2 = new System.Windows.Forms.Label();
            this.lblHome3 = new System.Windows.Forms.Label();
            this.lblHome4 = new System.Windows.Forms.Label();
            this.lblHome5 = new System.Windows.Forms.Label();
            this.lblHome6 = new System.Windows.Forms.Label();
            this.lblHome7 = new System.Windows.Forms.Label();
            this.lblHome8 = new System.Windows.Forms.Label();
            this.lblHome9 = new System.Windows.Forms.Label();
            this.lblVisitor1 = new System.Windows.Forms.Label();
            this.lblVisitor2 = new System.Windows.Forms.Label();
            this.lblVisitor3 = new System.Windows.Forms.Label();
            this.lblVisitor4 = new System.Windows.Forms.Label();
            this.lblVisitor5 = new System.Windows.Forms.Label();
            this.lblVisitor6 = new System.Windows.Forms.Label();
            this.lblVisitor7 = new System.Windows.Forms.Label();
            this.lblVisitor8 = new System.Windows.Forms.Label();
            this.lblVisitor9 = new System.Windows.Forms.Label();
            this.lblAtbat = new System.Windows.Forms.Label();
            this.lblOnfirst = new System.Windows.Forms.Label();
            this.lblOnsecond = new System.Windows.Forms.Label();
            this.lblOnthird = new System.Windows.Forms.Label();
            this.lblStatic1 = new System.Windows.Forms.Label();
            this.lblOuts = new System.Windows.Forms.Label();
            this.grpHomelineup = new System.Windows.Forms.GroupBox();
            this.lblHomepitcher = new System.Windows.Forms.Label();
            this.grpVislineup = new System.Windows.Forms.GroupBox();
            this.lblVispitcher = new System.Windows.Forms.Label();
            this.grpStatic2 = new System.Windows.Forms.GroupBox();
            this.lblStatic6 = new System.Windows.Forms.Label();
            this.lblStatic7 = new System.Windows.Forms.Label();
            this.lblStatic8 = new System.Windows.Forms.Label();
            this.lblStatic9 = new System.Windows.Forms.Label();
            this.lblVisruns = new System.Windows.Forms.Label();
            this.lblVishits = new System.Windows.Forms.Label();
            this.lblViserrors = new System.Windows.Forms.Label();
            this.lblHomeruns = new System.Windows.Forms.Label();
            this.lblHomehits = new System.Windows.Forms.Label();
            this.lblHomeerrors = new System.Windows.Forms.Label();
            this.lblStatic3 = new System.Windows.Forms.Label();
            this.lblStatic4 = new System.Windows.Forms.Label();
            this.lblStatic5 = new System.Windows.Forms.Label();
            this.lblVisitname = new System.Windows.Forms.Label();
            this.lblHomename = new System.Windows.Forms.Label();
            this.lblResult = new System.Windows.Forms.Label();
            this.btnNextatbat = new System.Windows.Forms.Button();
            this.lblVisitatbat = new System.Windows.Forms.Label();
            this.lblHomeatbat = new System.Windows.Forms.Label();
            this.lblStatic10 = new System.Windows.Forms.Label();
            this.lblInning = new System.Windows.Forms.Label();
            this.lblInning1 = new System.Windows.Forms.Label();
            this.lblInning2 = new System.Windows.Forms.Label();
            this.lblInning3 = new System.Windows.Forms.Label();
            this.lblInning4 = new System.Windows.Forms.Label();
            this.lblInning5 = new System.Windows.Forms.Label();
            this.lblInning6 = new System.Windows.Forms.Label();
            this.lblInning7 = new System.Windows.Forms.Label();
            this.lblInning8 = new System.Windows.Forms.Label();
            this.lblInning9 = new System.Windows.Forms.Label();
            this.lblInning10 = new System.Windows.Forms.Label();
            this.lblVisinning1 = new System.Windows.Forms.Label();
            this.lblVisinning2 = new System.Windows.Forms.Label();
            this.lblVisinning3 = new System.Windows.Forms.Label();
            this.lblVisinning4 = new System.Windows.Forms.Label();
            this.lblVisinning5 = new System.Windows.Forms.Label();
            this.lblVisinning6 = new System.Windows.Forms.Label();
            this.lblVisinning7 = new System.Windows.Forms.Label();
            this.lblVisinning8 = new System.Windows.Forms.Label();
            this.lblVisinning9 = new System.Windows.Forms.Label();
            this.lblVisinning10 = new System.Windows.Forms.Label();
            this.lblHomeinning1 = new System.Windows.Forms.Label();
            this.lblHomeinning2 = new System.Windows.Forms.Label();
            this.lblHomeinning3 = new System.Windows.Forms.Label();
            this.lblHomeinning4 = new System.Windows.Forms.Label();
            this.lblHomeinning5 = new System.Windows.Forms.Label();
            this.lblHomeinning6 = new System.Windows.Forms.Label();
            this.lblHomeinning7 = new System.Windows.Forms.Label();
            this.lblHomeinning8 = new System.Windows.Forms.Label();
            this.lblHomeinning9 = new System.Windows.Forms.Label();
            this.lblHomeinning10 = new System.Windows.Forms.Label();
            this.picStatic11 = new System.Windows.Forms.PictureBox();
            this.mnuMainframe = new System.Windows.Forms.MenuStrip();
            this.mnuFile = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileNew = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileOpen = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileSave = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileSaveAs = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.mnuAppExit = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuEdit = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuEditUndo = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuEditCut = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuEditCopy = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuEditPaste = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuView = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewToolbar = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewStatusBar = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuViewDoatbat = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewPlayLog = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewBoxscore = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewGamestats = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewSeasonstats = new System.Windows.Forms.ToolStripMenuItem();
            this.autoPlayLogToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.topTenToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.leagueToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.standingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loadLeagueToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.resetSeasonStatsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeams = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamsEdit = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamsCreate = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuVisiting = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamvSelect = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamvLineup = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamvStats = new System.Windows.Forms.ToolStripMenuItem();
            this.viewVisitingTeamMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.viewHomeTeamMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamhSelect = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamhLineup = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuTeamhStats = new System.Windows.Forms.ToolStripMenuItem();
            this.viewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.teamsViewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuGame = new System.Windows.Forms.ToolStripMenuItem();
            this.selectTeamsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuGamePlayball = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuGamePlaySimulated = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelp = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuAppAbout = new System.Windows.Forms.ToolStripMenuItem();
            this.grpHomelineup.SuspendLayout();
            this.grpVislineup.SuspendLayout();
            this.grpStatic2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picStatic11)).BeginInit();
            this.mnuMainframe.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblHome1
            // 
            this.lblHome1.Location = new System.Drawing.Point(14, 19);
            this.lblHome1.Name = "lblHome1";
            this.lblHome1.Size = new System.Drawing.Size(181, 13);
            this.lblHome1.TabIndex = 1;
            // 
            // lblHome2
            // 
            this.lblHome2.Location = new System.Drawing.Point(14, 40);
            this.lblHome2.Name = "lblHome2";
            this.lblHome2.Size = new System.Drawing.Size(181, 13);
            this.lblHome2.TabIndex = 2;
            // 
            // lblHome3
            // 
            this.lblHome3.Location = new System.Drawing.Point(14, 61);
            this.lblHome3.Name = "lblHome3";
            this.lblHome3.Size = new System.Drawing.Size(181, 13);
            this.lblHome3.TabIndex = 3;
            // 
            // lblHome4
            // 
            this.lblHome4.Location = new System.Drawing.Point(14, 82);
            this.lblHome4.Name = "lblHome4";
            this.lblHome4.Size = new System.Drawing.Size(181, 13);
            this.lblHome4.TabIndex = 4;
            // 
            // lblHome5
            // 
            this.lblHome5.Location = new System.Drawing.Point(14, 102);
            this.lblHome5.Name = "lblHome5";
            this.lblHome5.Size = new System.Drawing.Size(181, 13);
            this.lblHome5.TabIndex = 5;
            // 
            // lblHome6
            // 
            this.lblHome6.Location = new System.Drawing.Point(14, 123);
            this.lblHome6.Name = "lblHome6";
            this.lblHome6.Size = new System.Drawing.Size(181, 13);
            this.lblHome6.TabIndex = 6;
            // 
            // lblHome7
            // 
            this.lblHome7.Location = new System.Drawing.Point(14, 144);
            this.lblHome7.Name = "lblHome7";
            this.lblHome7.Size = new System.Drawing.Size(181, 13);
            this.lblHome7.TabIndex = 7;
            // 
            // lblHome8
            // 
            this.lblHome8.Location = new System.Drawing.Point(14, 165);
            this.lblHome8.Name = "lblHome8";
            this.lblHome8.Size = new System.Drawing.Size(181, 13);
            this.lblHome8.TabIndex = 8;
            // 
            // lblHome9
            // 
            this.lblHome9.Location = new System.Drawing.Point(14, 186);
            this.lblHome9.Name = "lblHome9";
            this.lblHome9.Size = new System.Drawing.Size(181, 13);
            this.lblHome9.TabIndex = 9;
            // 
            // lblVisitor1
            // 
            this.lblVisitor1.Location = new System.Drawing.Point(14, 20);
            this.lblVisitor1.Name = "lblVisitor1";
            this.lblVisitor1.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor1.TabIndex = 10;
            // 
            // lblVisitor2
            // 
            this.lblVisitor2.Location = new System.Drawing.Point(14, 40);
            this.lblVisitor2.Name = "lblVisitor2";
            this.lblVisitor2.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor2.TabIndex = 11;
            // 
            // lblVisitor3
            // 
            this.lblVisitor3.Location = new System.Drawing.Point(14, 61);
            this.lblVisitor3.Name = "lblVisitor3";
            this.lblVisitor3.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor3.TabIndex = 12;
            // 
            // lblVisitor4
            // 
            this.lblVisitor4.Location = new System.Drawing.Point(14, 82);
            this.lblVisitor4.Name = "lblVisitor4";
            this.lblVisitor4.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor4.TabIndex = 13;
            // 
            // lblVisitor5
            // 
            this.lblVisitor5.Location = new System.Drawing.Point(14, 103);
            this.lblVisitor5.Name = "lblVisitor5";
            this.lblVisitor5.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor5.TabIndex = 14;
            // 
            // lblVisitor6
            // 
            this.lblVisitor6.Location = new System.Drawing.Point(14, 124);
            this.lblVisitor6.Name = "lblVisitor6";
            this.lblVisitor6.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor6.TabIndex = 15;
            // 
            // lblVisitor7
            // 
            this.lblVisitor7.Location = new System.Drawing.Point(14, 144);
            this.lblVisitor7.Name = "lblVisitor7";
            this.lblVisitor7.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor7.TabIndex = 16;
            // 
            // lblVisitor8
            // 
            this.lblVisitor8.Location = new System.Drawing.Point(14, 165);
            this.lblVisitor8.Name = "lblVisitor8";
            this.lblVisitor8.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor8.TabIndex = 17;
            // 
            // lblVisitor9
            // 
            this.lblVisitor9.Location = new System.Drawing.Point(14, 186);
            this.lblVisitor9.Name = "lblVisitor9";
            this.lblVisitor9.Size = new System.Drawing.Size(181, 13);
            this.lblVisitor9.TabIndex = 18;
            // 
            // lblAtbat
            // 
            this.lblAtbat.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lblAtbat.Location = new System.Drawing.Point(119, 176);
            this.lblAtbat.Name = "lblAtbat";
            this.lblAtbat.Size = new System.Drawing.Size(110, 17);
            this.lblAtbat.TabIndex = 19;
            this.lblAtbat.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblOnfirst
            // 
            this.lblOnfirst.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lblOnfirst.Location = new System.Drawing.Point(232, 96);
            this.lblOnfirst.Name = "lblOnfirst";
            this.lblOnfirst.Size = new System.Drawing.Size(108, 17);
            this.lblOnfirst.TabIndex = 20;
            this.lblOnfirst.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblOnsecond
            // 
            this.lblOnsecond.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lblOnsecond.Location = new System.Drawing.Point(119, 16);
            this.lblOnsecond.Name = "lblOnsecond";
            this.lblOnsecond.Size = new System.Drawing.Size(108, 17);
            this.lblOnsecond.TabIndex = 21;
            this.lblOnsecond.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblOnthird
            // 
            this.lblOnthird.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lblOnthird.Location = new System.Drawing.Point(10, 96);
            this.lblOnthird.Name = "lblOnthird";
            this.lblOnthird.Size = new System.Drawing.Size(108, 17);
            this.lblOnthird.TabIndex = 22;
            this.lblOnthird.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblStatic1
            // 
            this.lblStatic1.Location = new System.Drawing.Point(450, 348);
            this.lblStatic1.Name = "lblStatic1";
            this.lblStatic1.Size = new System.Drawing.Size(29, 17);
            this.lblStatic1.TabIndex = 23;
            this.lblStatic1.Text = "Outs";
            this.lblStatic1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblOuts
            // 
            this.lblOuts.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblOuts.Location = new System.Drawing.Point(480, 348);
            this.lblOuts.Name = "lblOuts";
            this.lblOuts.Size = new System.Drawing.Size(16, 17);
            this.lblOuts.TabIndex = 24;
            this.lblOuts.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // grpHomelineup
            // 
            this.grpHomelineup.Controls.Add(this.lblHome1);
            this.grpHomelineup.Controls.Add(this.lblHome2);
            this.grpHomelineup.Controls.Add(this.lblHome3);
            this.grpHomelineup.Controls.Add(this.lblHome4);
            this.grpHomelineup.Controls.Add(this.lblHome5);
            this.grpHomelineup.Controls.Add(this.lblHome6);
            this.grpHomelineup.Controls.Add(this.lblHome7);
            this.grpHomelineup.Controls.Add(this.lblHome8);
            this.grpHomelineup.Controls.Add(this.lblHome9);
            this.grpHomelineup.Controls.Add(this.lblHomepitcher);
            this.grpHomelineup.Location = new System.Drawing.Point(6, 282);
            this.grpHomelineup.Name = "grpHomelineup";
            this.grpHomelineup.Size = new System.Drawing.Size(201, 252);
            this.grpHomelineup.TabIndex = 25;
            this.grpHomelineup.TabStop = false;
            this.grpHomelineup.Text = "HOME";
            // 
            // lblHomepitcher
            // 
            this.lblHomepitcher.Location = new System.Drawing.Point(14, 216);
            this.lblHomepitcher.Name = "lblHomepitcher";
            this.lblHomepitcher.Size = new System.Drawing.Size(181, 13);
            this.lblHomepitcher.TabIndex = 43;
            // 
            // grpVislineup
            // 
            this.grpVislineup.Controls.Add(this.lblVisitor1);
            this.grpVislineup.Controls.Add(this.lblVisitor2);
            this.grpVislineup.Controls.Add(this.lblVisitor3);
            this.grpVislineup.Controls.Add(this.lblVisitor4);
            this.grpVislineup.Controls.Add(this.lblVisitor5);
            this.grpVislineup.Controls.Add(this.lblVisitor6);
            this.grpVislineup.Controls.Add(this.lblVisitor7);
            this.grpVislineup.Controls.Add(this.lblVisitor8);
            this.grpVislineup.Controls.Add(this.lblVisitor9);
            this.grpVislineup.Controls.Add(this.lblVispitcher);
            this.grpVislineup.Location = new System.Drawing.Point(6, 26);
            this.grpVislineup.Name = "grpVislineup";
            this.grpVislineup.Size = new System.Drawing.Size(201, 250);
            this.grpVislineup.TabIndex = 26;
            this.grpVislineup.TabStop = false;
            this.grpVislineup.Text = "VISITOR";
            // 
            // lblVispitcher
            // 
            this.lblVispitcher.Location = new System.Drawing.Point(14, 216);
            this.lblVispitcher.Name = "lblVispitcher";
            this.lblVispitcher.Size = new System.Drawing.Size(181, 13);
            this.lblVispitcher.TabIndex = 44;
            // 
            // grpStatic2
            // 
            this.grpStatic2.Controls.Add(this.lblAtbat);
            this.grpStatic2.Controls.Add(this.lblOnfirst);
            this.grpStatic2.Controls.Add(this.lblOnsecond);
            this.grpStatic2.Controls.Add(this.lblOnthird);
            this.grpStatic2.Controls.Add(this.lblStatic6);
            this.grpStatic2.Controls.Add(this.lblStatic7);
            this.grpStatic2.Controls.Add(this.lblStatic8);
            this.grpStatic2.Controls.Add(this.lblStatic9);
            this.grpStatic2.Location = new System.Drawing.Point(322, 25);
            this.grpStatic2.Name = "grpStatic2";
            this.grpStatic2.Size = new System.Drawing.Size(348, 230);
            this.grpStatic2.TabIndex = 27;
            this.grpStatic2.TabStop = false;
            // 
            // lblStatic6
            // 
            this.lblStatic6.AutoSize = true;
            this.lblStatic6.Location = new System.Drawing.Point(162, 197);
            this.lblStatic6.Name = "lblStatic6";
            this.lblStatic6.Size = new System.Drawing.Size(35, 13);
            this.lblStatic6.TabIndex = 39;
            this.lblStatic6.Text = "Home";
            // 
            // lblStatic7
            // 
            this.lblStatic7.AutoSize = true;
            this.lblStatic7.Location = new System.Drawing.Point(281, 115);
            this.lblStatic7.Name = "lblStatic7";
            this.lblStatic7.Size = new System.Drawing.Size(21, 13);
            this.lblStatic7.TabIndex = 40;
            this.lblStatic7.Text = "1st";
            // 
            // lblStatic8
            // 
            this.lblStatic8.AutoSize = true;
            this.lblStatic8.Location = new System.Drawing.Point(160, 37);
            this.lblStatic8.Name = "lblStatic8";
            this.lblStatic8.Size = new System.Drawing.Size(25, 13);
            this.lblStatic8.TabIndex = 41;
            this.lblStatic8.Text = "2nd";
            // 
            // lblStatic9
            // 
            this.lblStatic9.AutoSize = true;
            this.lblStatic9.Location = new System.Drawing.Point(47, 117);
            this.lblStatic9.Name = "lblStatic9";
            this.lblStatic9.Size = new System.Drawing.Size(22, 13);
            this.lblStatic9.TabIndex = 42;
            this.lblStatic9.Text = "3rd";
            // 
            // lblVisruns
            // 
            this.lblVisruns.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisruns.Location = new System.Drawing.Point(604, 286);
            this.lblVisruns.Name = "lblVisruns";
            this.lblVisruns.Size = new System.Drawing.Size(22, 17);
            this.lblVisruns.TabIndex = 28;
            this.lblVisruns.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVishits
            // 
            this.lblVishits.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVishits.Location = new System.Drawing.Point(634, 286);
            this.lblVishits.Name = "lblVishits";
            this.lblVishits.Size = new System.Drawing.Size(22, 17);
            this.lblVishits.TabIndex = 29;
            this.lblVishits.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblViserrors
            // 
            this.lblViserrors.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblViserrors.Location = new System.Drawing.Point(664, 286);
            this.lblViserrors.Name = "lblViserrors";
            this.lblViserrors.Size = new System.Drawing.Size(22, 17);
            this.lblViserrors.TabIndex = 30;
            this.lblViserrors.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeruns
            // 
            this.lblHomeruns.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeruns.Location = new System.Drawing.Point(604, 308);
            this.lblHomeruns.Name = "lblHomeruns";
            this.lblHomeruns.Size = new System.Drawing.Size(22, 17);
            this.lblHomeruns.TabIndex = 31;
            this.lblHomeruns.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomehits
            // 
            this.lblHomehits.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomehits.Location = new System.Drawing.Point(634, 308);
            this.lblHomehits.Name = "lblHomehits";
            this.lblHomehits.Size = new System.Drawing.Size(22, 17);
            this.lblHomehits.TabIndex = 32;
            this.lblHomehits.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeerrors
            // 
            this.lblHomeerrors.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeerrors.Location = new System.Drawing.Point(664, 308);
            this.lblHomeerrors.Name = "lblHomeerrors";
            this.lblHomeerrors.Size = new System.Drawing.Size(22, 17);
            this.lblHomeerrors.TabIndex = 33;
            this.lblHomeerrors.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblStatic3
            // 
            this.lblStatic3.AutoSize = true;
            this.lblStatic3.Location = new System.Drawing.Point(609, 266);
            this.lblStatic3.Name = "lblStatic3";
            this.lblStatic3.Size = new System.Drawing.Size(15, 13);
            this.lblStatic3.TabIndex = 34;
            this.lblStatic3.Text = "R";
            // 
            // lblStatic4
            // 
            this.lblStatic4.AutoSize = true;
            this.lblStatic4.Location = new System.Drawing.Point(639, 266);
            this.lblStatic4.Name = "lblStatic4";
            this.lblStatic4.Size = new System.Drawing.Size(15, 13);
            this.lblStatic4.TabIndex = 35;
            this.lblStatic4.Text = "H";
            // 
            // lblStatic5
            // 
            this.lblStatic5.AutoSize = true;
            this.lblStatic5.Location = new System.Drawing.Point(669, 266);
            this.lblStatic5.Name = "lblStatic5";
            this.lblStatic5.Size = new System.Drawing.Size(14, 13);
            this.lblStatic5.TabIndex = 36;
            this.lblStatic5.Text = "E";
            // 
            // lblVisitname
            // 
            this.lblVisitname.Location = new System.Drawing.Point(273, 287);
            this.lblVisitname.Name = "lblVisitname";
            this.lblVisitname.Size = new System.Drawing.Size(33, 14);
            this.lblVisitname.TabIndex = 37;
            this.lblVisitname.TextAlign = System.Drawing.ContentAlignment.TopRight;
            // 
            // lblHomename
            // 
            this.lblHomename.Location = new System.Drawing.Point(273, 310);
            this.lblHomename.Name = "lblHomename";
            this.lblHomename.Size = new System.Drawing.Size(32, 14);
            this.lblHomename.TabIndex = 38;
            this.lblHomename.TextAlign = System.Drawing.ContentAlignment.TopRight;
            // 
            // lblResult
            // 
            this.lblResult.Location = new System.Drawing.Point(322, 380);
            this.lblResult.Name = "lblResult";
            this.lblResult.Size = new System.Drawing.Size(348, 98);
            this.lblResult.TabIndex = 45;
            // 
            // btnNextatbat
            // 
            this.btnNextatbat.Enabled = false;
            this.btnNextatbat.Location = new System.Drawing.Point(466, 484);
            this.btnNextatbat.Name = "btnNextatbat";
            this.btnNextatbat.Size = new System.Drawing.Size(75, 24);
            this.btnNextatbat.TabIndex = 46;
            this.btnNextatbat.Text = "Next At Bat";
            this.btnNextatbat.Click += new System.EventHandler(this.btnNextatbat_Click);
            // 
            // lblVisitatbat
            // 
            this.lblVisitatbat.Location = new System.Drawing.Point(249, 287);
            this.lblVisitatbat.Name = "lblVisitatbat";
            this.lblVisitatbat.Size = new System.Drawing.Size(12, 14);
            this.lblVisitatbat.TabIndex = 47;
            this.lblVisitatbat.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblHomeatbat
            // 
            this.lblHomeatbat.Location = new System.Drawing.Point(249, 310);
            this.lblHomeatbat.Name = "lblHomeatbat";
            this.lblHomeatbat.Size = new System.Drawing.Size(12, 14);
            this.lblHomeatbat.TabIndex = 48;
            this.lblHomeatbat.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblStatic10
            // 
            this.lblStatic10.Location = new System.Drawing.Point(532, 348);
            this.lblStatic10.Name = "lblStatic10";
            this.lblStatic10.Size = new System.Drawing.Size(25, 17);
            this.lblStatic10.TabIndex = 49;
            this.lblStatic10.Text = "Inn.";
            this.lblStatic10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblInning
            // 
            this.lblInning.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblInning.Location = new System.Drawing.Point(561, 348);
            this.lblInning.Name = "lblInning";
            this.lblInning.Size = new System.Drawing.Size(20, 17);
            this.lblInning.TabIndex = 50;
            this.lblInning.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblInning1
            // 
            this.lblInning1.Location = new System.Drawing.Point(326, 266);
            this.lblInning1.Name = "lblInning1";
            this.lblInning1.Size = new System.Drawing.Size(21, 14);
            this.lblInning1.TabIndex = 51;
            this.lblInning1.Text = "1";
            this.lblInning1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning2
            // 
            this.lblInning2.Location = new System.Drawing.Point(352, 266);
            this.lblInning2.Name = "lblInning2";
            this.lblInning2.Size = new System.Drawing.Size(21, 14);
            this.lblInning2.TabIndex = 52;
            this.lblInning2.Text = "2";
            this.lblInning2.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning3
            // 
            this.lblInning3.Location = new System.Drawing.Point(378, 266);
            this.lblInning3.Name = "lblInning3";
            this.lblInning3.Size = new System.Drawing.Size(21, 14);
            this.lblInning3.TabIndex = 53;
            this.lblInning3.Text = "3";
            this.lblInning3.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning4
            // 
            this.lblInning4.Location = new System.Drawing.Point(404, 266);
            this.lblInning4.Name = "lblInning4";
            this.lblInning4.Size = new System.Drawing.Size(21, 14);
            this.lblInning4.TabIndex = 54;
            this.lblInning4.Text = "4";
            this.lblInning4.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning5
            // 
            this.lblInning5.Location = new System.Drawing.Point(430, 266);
            this.lblInning5.Name = "lblInning5";
            this.lblInning5.Size = new System.Drawing.Size(21, 14);
            this.lblInning5.TabIndex = 55;
            this.lblInning5.Text = "5";
            this.lblInning5.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning6
            // 
            this.lblInning6.Location = new System.Drawing.Point(456, 266);
            this.lblInning6.Name = "lblInning6";
            this.lblInning6.Size = new System.Drawing.Size(21, 14);
            this.lblInning6.TabIndex = 56;
            this.lblInning6.Text = "6";
            this.lblInning6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning7
            // 
            this.lblInning7.Location = new System.Drawing.Point(482, 266);
            this.lblInning7.Name = "lblInning7";
            this.lblInning7.Size = new System.Drawing.Size(21, 14);
            this.lblInning7.TabIndex = 57;
            this.lblInning7.Text = "7";
            this.lblInning7.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning8
            // 
            this.lblInning8.Location = new System.Drawing.Point(508, 266);
            this.lblInning8.Name = "lblInning8";
            this.lblInning8.Size = new System.Drawing.Size(21, 14);
            this.lblInning8.TabIndex = 58;
            this.lblInning8.Text = "8";
            this.lblInning8.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning9
            // 
            this.lblInning9.Location = new System.Drawing.Point(534, 266);
            this.lblInning9.Name = "lblInning9";
            this.lblInning9.Size = new System.Drawing.Size(21, 14);
            this.lblInning9.TabIndex = 59;
            this.lblInning9.Text = "9";
            this.lblInning9.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblInning10
            // 
            this.lblInning10.Location = new System.Drawing.Point(560, 266);
            this.lblInning10.Name = "lblInning10";
            this.lblInning10.Size = new System.Drawing.Size(21, 14);
            this.lblInning10.TabIndex = 60;
            this.lblInning10.Text = "10";
            this.lblInning10.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning1
            // 
            this.lblVisinning1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning1.Location = new System.Drawing.Point(327, 286);
            this.lblVisinning1.Name = "lblVisinning1";
            this.lblVisinning1.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning1.TabIndex = 61;
            this.lblVisinning1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning2
            // 
            this.lblVisinning2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning2.Location = new System.Drawing.Point(353, 286);
            this.lblVisinning2.Name = "lblVisinning2";
            this.lblVisinning2.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning2.TabIndex = 62;
            this.lblVisinning2.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning3
            // 
            this.lblVisinning3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning3.Location = new System.Drawing.Point(379, 286);
            this.lblVisinning3.Name = "lblVisinning3";
            this.lblVisinning3.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning3.TabIndex = 63;
            this.lblVisinning3.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning4
            // 
            this.lblVisinning4.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning4.Location = new System.Drawing.Point(405, 286);
            this.lblVisinning4.Name = "lblVisinning4";
            this.lblVisinning4.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning4.TabIndex = 64;
            this.lblVisinning4.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning5
            // 
            this.lblVisinning5.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning5.Location = new System.Drawing.Point(431, 286);
            this.lblVisinning5.Name = "lblVisinning5";
            this.lblVisinning5.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning5.TabIndex = 65;
            this.lblVisinning5.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning6
            // 
            this.lblVisinning6.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning6.Location = new System.Drawing.Point(457, 286);
            this.lblVisinning6.Name = "lblVisinning6";
            this.lblVisinning6.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning6.TabIndex = 66;
            this.lblVisinning6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning7
            // 
            this.lblVisinning7.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning7.Location = new System.Drawing.Point(483, 286);
            this.lblVisinning7.Name = "lblVisinning7";
            this.lblVisinning7.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning7.TabIndex = 67;
            this.lblVisinning7.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning8
            // 
            this.lblVisinning8.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning8.Location = new System.Drawing.Point(509, 286);
            this.lblVisinning8.Name = "lblVisinning8";
            this.lblVisinning8.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning8.TabIndex = 68;
            this.lblVisinning8.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning9
            // 
            this.lblVisinning9.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning9.Location = new System.Drawing.Point(535, 286);
            this.lblVisinning9.Name = "lblVisinning9";
            this.lblVisinning9.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning9.TabIndex = 69;
            this.lblVisinning9.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblVisinning10
            // 
            this.lblVisinning10.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblVisinning10.Location = new System.Drawing.Point(560, 286);
            this.lblVisinning10.Name = "lblVisinning10";
            this.lblVisinning10.Size = new System.Drawing.Size(20, 17);
            this.lblVisinning10.TabIndex = 70;
            this.lblVisinning10.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning1
            // 
            this.lblHomeinning1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning1.Location = new System.Drawing.Point(327, 308);
            this.lblHomeinning1.Name = "lblHomeinning1";
            this.lblHomeinning1.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning1.TabIndex = 71;
            this.lblHomeinning1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning2
            // 
            this.lblHomeinning2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning2.Location = new System.Drawing.Point(353, 308);
            this.lblHomeinning2.Name = "lblHomeinning2";
            this.lblHomeinning2.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning2.TabIndex = 72;
            this.lblHomeinning2.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning3
            // 
            this.lblHomeinning3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning3.Location = new System.Drawing.Point(379, 308);
            this.lblHomeinning3.Name = "lblHomeinning3";
            this.lblHomeinning3.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning3.TabIndex = 73;
            this.lblHomeinning3.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning4
            // 
            this.lblHomeinning4.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning4.Location = new System.Drawing.Point(405, 308);
            this.lblHomeinning4.Name = "lblHomeinning4";
            this.lblHomeinning4.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning4.TabIndex = 74;
            this.lblHomeinning4.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning5
            // 
            this.lblHomeinning5.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning5.Location = new System.Drawing.Point(431, 308);
            this.lblHomeinning5.Name = "lblHomeinning5";
            this.lblHomeinning5.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning5.TabIndex = 75;
            this.lblHomeinning5.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning6
            // 
            this.lblHomeinning6.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning6.Location = new System.Drawing.Point(457, 308);
            this.lblHomeinning6.Name = "lblHomeinning6";
            this.lblHomeinning6.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning6.TabIndex = 76;
            this.lblHomeinning6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning7
            // 
            this.lblHomeinning7.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning7.Location = new System.Drawing.Point(483, 308);
            this.lblHomeinning7.Name = "lblHomeinning7";
            this.lblHomeinning7.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning7.TabIndex = 77;
            this.lblHomeinning7.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning8
            // 
            this.lblHomeinning8.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning8.Location = new System.Drawing.Point(509, 308);
            this.lblHomeinning8.Name = "lblHomeinning8";
            this.lblHomeinning8.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning8.TabIndex = 78;
            this.lblHomeinning8.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning9
            // 
            this.lblHomeinning9.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning9.Location = new System.Drawing.Point(535, 308);
            this.lblHomeinning9.Name = "lblHomeinning9";
            this.lblHomeinning9.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning9.TabIndex = 79;
            this.lblHomeinning9.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblHomeinning10
            // 
            this.lblHomeinning10.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblHomeinning10.Location = new System.Drawing.Point(561, 308);
            this.lblHomeinning10.Name = "lblHomeinning10";
            this.lblHomeinning10.Size = new System.Drawing.Size(20, 17);
            this.lblHomeinning10.TabIndex = 80;
            this.lblHomeinning10.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // picStatic11
            // 
            this.picStatic11.BackColor = System.Drawing.Color.Black;
            this.picStatic11.Location = new System.Drawing.Point(592, 282);
            this.picStatic11.Name = "picStatic11";
            this.picStatic11.Size = new System.Drawing.Size(2, 46);
            this.picStatic11.TabIndex = 81;
            this.picStatic11.TabStop = false;
            // 
            // mnuMainframe
            // 
            this.mnuMainframe.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuFile,
            this.mnuEdit,
            this.mnuView,
            this.leagueToolStripMenuItem,
            this.mnuTeams,
            this.mnuGame,
            this.mnuHelp});
            this.mnuMainframe.Location = new System.Drawing.Point(0, 0);
            this.mnuMainframe.Name = "mnuMainframe";
            this.mnuMainframe.Size = new System.Drawing.Size(720, 24);
            this.mnuMainframe.TabIndex = 0;
            this.mnuMainframe.Text = "mnuMainframe";
            // 
            // mnuFile
            // 
            this.mnuFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuFileNew,
            this.mnuFileOpen,
            this.mnuFileSave,
            this.mnuFileSaveAs,
            this.mnuSeparator,
            this.mnuAppExit});
            this.mnuFile.Name = "mnuFile";
            this.mnuFile.Size = new System.Drawing.Size(37, 20);
            this.mnuFile.Text = "&File";
            // 
            // mnuFileNew
            // 
            this.mnuFileNew.Name = "mnuFileNew";
            this.mnuFileNew.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
            this.mnuFileNew.Size = new System.Drawing.Size(155, 22);
            this.mnuFileNew.Text = "&New";
            // 
            // mnuFileOpen
            // 
            this.mnuFileOpen.Name = "mnuFileOpen";
            this.mnuFileOpen.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O)));
            this.mnuFileOpen.Size = new System.Drawing.Size(155, 22);
            this.mnuFileOpen.Text = "&Open...";
            // 
            // mnuFileSave
            // 
            this.mnuFileSave.Name = "mnuFileSave";
            this.mnuFileSave.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
            this.mnuFileSave.Size = new System.Drawing.Size(155, 22);
            this.mnuFileSave.Text = "&Save";
            // 
            // mnuFileSaveAs
            // 
            this.mnuFileSaveAs.Name = "mnuFileSaveAs";
            this.mnuFileSaveAs.Size = new System.Drawing.Size(155, 22);
            this.mnuFileSaveAs.Text = "Save &As...";
            // 
            // mnuSeparator
            // 
            this.mnuSeparator.Name = "mnuSeparator";
            this.mnuSeparator.Size = new System.Drawing.Size(152, 6);
            // 
            // mnuAppExit
            // 
            this.mnuAppExit.Name = "mnuAppExit";
            this.mnuAppExit.Size = new System.Drawing.Size(155, 22);
            this.mnuAppExit.Text = "E&xit";
            // 
            // mnuEdit
            // 
            this.mnuEdit.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuEditUndo,
            this.mnuSeparator1,
            this.mnuEditCut,
            this.mnuEditCopy,
            this.mnuEditPaste,
            this.mnuSeparator2});
            this.mnuEdit.Name = "mnuEdit";
            this.mnuEdit.Size = new System.Drawing.Size(39, 20);
            this.mnuEdit.Text = "&Edit";
            // 
            // mnuEditUndo
            // 
            this.mnuEditUndo.Name = "mnuEditUndo";
            this.mnuEditUndo.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Z)));
            this.mnuEditUndo.Size = new System.Drawing.Size(144, 22);
            this.mnuEditUndo.Text = "&Undo";
            // 
            // mnuSeparator1
            // 
            this.mnuSeparator1.Name = "mnuSeparator1";
            this.mnuSeparator1.Size = new System.Drawing.Size(141, 6);
            // 
            // mnuEditCut
            // 
            this.mnuEditCut.Name = "mnuEditCut";
            this.mnuEditCut.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.X)));
            this.mnuEditCut.Size = new System.Drawing.Size(144, 22);
            this.mnuEditCut.Text = "Cu&t";
            // 
            // mnuEditCopy
            // 
            this.mnuEditCopy.Name = "mnuEditCopy";
            this.mnuEditCopy.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
            this.mnuEditCopy.Size = new System.Drawing.Size(144, 22);
            this.mnuEditCopy.Text = "&Copy";
            // 
            // mnuEditPaste
            // 
            this.mnuEditPaste.Name = "mnuEditPaste";
            this.mnuEditPaste.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.V)));
            this.mnuEditPaste.Size = new System.Drawing.Size(144, 22);
            this.mnuEditPaste.Text = "&Paste";
            // 
            // mnuSeparator2
            // 
            this.mnuSeparator2.Name = "mnuSeparator2";
            this.mnuSeparator2.Size = new System.Drawing.Size(141, 6);
            // 
            // mnuView
            // 
            this.mnuView.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuViewToolbar,
            this.mnuViewStatusBar,
            this.mnuSeparator3,
            this.mnuViewDoatbat,
            this.mnuViewPlayLog,
            this.mnuViewBoxscore,
            this.mnuViewGamestats,
            this.mnuViewSeasonstats,
            this.autoPlayLogToolStripMenuItem,
            this.topTenToolStripMenuItem});
            this.mnuView.Name = "mnuView";
            this.mnuView.Size = new System.Drawing.Size(44, 20);
            this.mnuView.Text = "&View";
            // 
            // mnuViewToolbar
            // 
            this.mnuViewToolbar.Name = "mnuViewToolbar";
            this.mnuViewToolbar.Size = new System.Drawing.Size(148, 22);
            this.mnuViewToolbar.Text = "&Toolbar";
            // 
            // mnuViewStatusBar
            // 
            this.mnuViewStatusBar.Name = "mnuViewStatusBar";
            this.mnuViewStatusBar.Size = new System.Drawing.Size(148, 22);
            this.mnuViewStatusBar.Text = "&Status Bar";
            // 
            // mnuSeparator3
            // 
            this.mnuSeparator3.Name = "mnuSeparator3";
            this.mnuSeparator3.Size = new System.Drawing.Size(145, 6);
            // 
            // mnuViewDoatbat
            // 
            this.mnuViewDoatbat.Name = "mnuViewDoatbat";
            this.mnuViewDoatbat.Size = new System.Drawing.Size(148, 22);
            this.mnuViewDoatbat.Text = "Do At Bat";
            // 
            // mnuViewPlayLog
            // 
            this.mnuViewPlayLog.Name = "mnuViewPlayLog";
            this.mnuViewPlayLog.Size = new System.Drawing.Size(148, 22);
            this.mnuViewPlayLog.Text = "&Play Log...";
            this.mnuViewPlayLog.Click += new System.EventHandler(this.mnuViewPlayLog_Click);
            // 
            // mnuViewBoxscore
            // 
            this.mnuViewBoxscore.Name = "mnuViewBoxscore";
            this.mnuViewBoxscore.Size = new System.Drawing.Size(148, 22);
            this.mnuViewBoxscore.Text = "&Box Score...";
            // 
            // mnuViewGamestats
            // 
            this.mnuViewGamestats.Name = "mnuViewGamestats";
            this.mnuViewGamestats.Size = new System.Drawing.Size(148, 22);
            this.mnuViewGamestats.Text = "&Game Stats...";
            this.mnuViewGamestats.Click += new System.EventHandler(this.mnuViewGamestats_Click);
            // 
            // mnuViewSeasonstats
            // 
            this.mnuViewSeasonstats.Name = "mnuViewSeasonstats";
            this.mnuViewSeasonstats.Size = new System.Drawing.Size(148, 22);
            this.mnuViewSeasonstats.Text = "S&eason Stats...";
            this.mnuViewSeasonstats.Click += new System.EventHandler(this.mnuViewSeasonstats_Click);
            // 
            // autoPlayLogToolStripMenuItem
            // 
            this.autoPlayLogToolStripMenuItem.Name = "autoPlayLogToolStripMenuItem";
            this.autoPlayLogToolStripMenuItem.Size = new System.Drawing.Size(148, 22);
            this.autoPlayLogToolStripMenuItem.Text = "Auto Play Log";
            this.autoPlayLogToolStripMenuItem.Click += new System.EventHandler(this.autoPlayLogToolStripMenuItem_Click);
            // 
            // topTenToolStripMenuItem
            // 
            this.topTenToolStripMenuItem.Name = "topTenToolStripMenuItem";
            this.topTenToolStripMenuItem.Size = new System.Drawing.Size(148, 22);
            this.topTenToolStripMenuItem.Text = "Top Ten...";
            this.topTenToolStripMenuItem.Click += new System.EventHandler(this.topTenToolStripMenuItem_Click);
            // 
            // leagueToolStripMenuItem
            // 
            this.leagueToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.standingsToolStripMenuItem,
            this.loadLeagueToolStripMenuItem,
            this.resetSeasonStatsToolStripMenuItem});
            this.leagueToolStripMenuItem.Name = "leagueToolStripMenuItem";
            this.leagueToolStripMenuItem.Size = new System.Drawing.Size(57, 20);
            this.leagueToolStripMenuItem.Text = "League";
            // 
            // standingsToolStripMenuItem
            // 
            this.standingsToolStripMenuItem.Enabled = false;
            this.standingsToolStripMenuItem.Name = "standingsToolStripMenuItem";
            this.standingsToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.standingsToolStripMenuItem.Text = "Standings...";
            this.standingsToolStripMenuItem.Click += new System.EventHandler(this.standingsToolStripMenuItem_Click);
            // 
            // loadLeagueToolStripMenuItem
            // 
            this.loadLeagueToolStripMenuItem.Name = "loadLeagueToolStripMenuItem";
            this.loadLeagueToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.loadLeagueToolStripMenuItem.Text = "&Load League";
            this.loadLeagueToolStripMenuItem.Click += new System.EventHandler(this.loadLeagueToolStripMenuItem_Click);
            // 
            // resetSeasonStatsToolStripMenuItem
            // 
            this.resetSeasonStatsToolStripMenuItem.Enabled = false;
            this.resetSeasonStatsToolStripMenuItem.Name = "resetSeasonStatsToolStripMenuItem";
            this.resetSeasonStatsToolStripMenuItem.Size = new System.Drawing.Size(170, 22);
            this.resetSeasonStatsToolStripMenuItem.Text = "&Reset Season Stats";
            this.resetSeasonStatsToolStripMenuItem.Click += new System.EventHandler(this.resetSeasonStatsToolStripMenuItem_Click);
            // 
            // mnuTeams
            // 
            this.mnuTeams.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuTeamsEdit,
            this.mnuTeamsCreate,
            this.mnuVisiting,
            this.viewHomeTeamMenuItem,
            this.teamsViewToolStripMenuItem});
            this.mnuTeams.Name = "mnuTeams";
            this.mnuTeams.Size = new System.Drawing.Size(54, 20);
            this.mnuTeams.Text = "Teams";
            // 
            // mnuTeamsEdit
            // 
            this.mnuTeamsEdit.Name = "mnuTeamsEdit";
            this.mnuTeamsEdit.Size = new System.Drawing.Size(120, 22);
            this.mnuTeamsEdit.Text = "&Edit...";
            // 
            // mnuTeamsCreate
            // 
            this.mnuTeamsCreate.Name = "mnuTeamsCreate";
            this.mnuTeamsCreate.Size = new System.Drawing.Size(120, 22);
            this.mnuTeamsCreate.Text = "&Create ...";
            this.mnuTeamsCreate.Click += new System.EventHandler(this.mnuTeamsCreate_Click);
            // 
            // mnuVisiting
            // 
            this.mnuVisiting.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuTeamvSelect,
            this.mnuTeamvLineup,
            this.mnuTeamvStats,
            this.viewVisitingTeamMenuItem});
            this.mnuVisiting.Name = "mnuVisiting";
            this.mnuVisiting.Size = new System.Drawing.Size(120, 22);
            this.mnuVisiting.Text = "&Visiting";
            // 
            // mnuTeamvSelect
            // 
            this.mnuTeamvSelect.Enabled = false;
            this.mnuTeamvSelect.Name = "mnuTeamvSelect";
            this.mnuTeamvSelect.Size = new System.Drawing.Size(129, 22);
            this.mnuTeamvSelect.Text = "Select";
            // 
            // mnuTeamvLineup
            // 
            this.mnuTeamvLineup.Name = "mnuTeamvLineup";
            this.mnuTeamvLineup.Size = new System.Drawing.Size(129, 22);
            this.mnuTeamvLineup.Text = "Set Lineup";
            this.mnuTeamvLineup.Click += new System.EventHandler(this.mnuTeamvLineup_Click);
            // 
            // mnuTeamvStats
            // 
            this.mnuTeamvStats.Name = "mnuTeamvStats";
            this.mnuTeamvStats.Size = new System.Drawing.Size(129, 22);
            this.mnuTeamvStats.Text = "Statistics...";
            // 
            // viewVisitingTeamMenuItem
            // 
            this.viewVisitingTeamMenuItem.Name = "viewVisitingTeamMenuItem";
            this.viewVisitingTeamMenuItem.Size = new System.Drawing.Size(129, 22);
            this.viewVisitingTeamMenuItem.Text = "View...";
            this.viewVisitingTeamMenuItem.Click += new System.EventHandler(this.viewVisitingTeamMenuItem_Click);
            // 
            // viewHomeTeamMenuItem
            // 
            this.viewHomeTeamMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuTeamhSelect,
            this.mnuTeamhLineup,
            this.mnuTeamhStats,
            this.viewToolStripMenuItem});
            this.viewHomeTeamMenuItem.Name = "viewHomeTeamMenuItem";
            this.viewHomeTeamMenuItem.Size = new System.Drawing.Size(120, 22);
            this.viewHomeTeamMenuItem.Text = "&Home";
            // 
            // mnuTeamhSelect
            // 
            this.mnuTeamhSelect.Name = "mnuTeamhSelect";
            this.mnuTeamhSelect.Size = new System.Drawing.Size(129, 22);
            this.mnuTeamhSelect.Text = "Select";
            // 
            // mnuTeamhLineup
            // 
            this.mnuTeamhLineup.Name = "mnuTeamhLineup";
            this.mnuTeamhLineup.Size = new System.Drawing.Size(129, 22);
            this.mnuTeamhLineup.Text = "Set Lineup";
            this.mnuTeamhLineup.Click += new System.EventHandler(this.mnuTeamhLineup_Click);
            // 
            // mnuTeamhStats
            // 
            this.mnuTeamhStats.Name = "mnuTeamhStats";
            this.mnuTeamhStats.Size = new System.Drawing.Size(129, 22);
            this.mnuTeamhStats.Text = "Statistics";
            // 
            // viewToolStripMenuItem
            // 
            this.viewToolStripMenuItem.Name = "viewToolStripMenuItem";
            this.viewToolStripMenuItem.Size = new System.Drawing.Size(129, 22);
            this.viewToolStripMenuItem.Text = "View...";
            this.viewToolStripMenuItem.Click += new System.EventHandler(this.viewToolStripMenuItem_Click);
            // 
            // teamsViewToolStripMenuItem
            // 
            this.teamsViewToolStripMenuItem.Name = "teamsViewToolStripMenuItem";
            this.teamsViewToolStripMenuItem.Size = new System.Drawing.Size(120, 22);
            this.teamsViewToolStripMenuItem.Text = "&View";
            // 
            // mnuGame
            // 
            this.mnuGame.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.selectTeamsToolStripMenuItem,
            this.mnuGamePlayball,
            this.mnuGamePlaySimulated});
            this.mnuGame.Name = "mnuGame";
            this.mnuGame.Size = new System.Drawing.Size(50, 20);
            this.mnuGame.Text = "&Game";
            // 
            // selectTeamsToolStripMenuItem
            // 
            this.selectTeamsToolStripMenuItem.Enabled = false;
            this.selectTeamsToolStripMenuItem.Name = "selectTeamsToolStripMenuItem";
            this.selectTeamsToolStripMenuItem.Size = new System.Drawing.Size(186, 22);
            this.selectTeamsToolStripMenuItem.Text = "&Select Teams";
            this.selectTeamsToolStripMenuItem.Click += new System.EventHandler(this.selectTeamsToolStripMenuItem_Click);
            // 
            // mnuGamePlayball
            // 
            this.mnuGamePlayball.Enabled = false;
            this.mnuGamePlayball.Name = "mnuGamePlayball";
            this.mnuGamePlayball.Size = new System.Drawing.Size(186, 22);
            this.mnuGamePlayball.Text = "&Play Ball";
            this.mnuGamePlayball.Click += new System.EventHandler(this.mnuGamePlayball_Click);
            // 
            // mnuGamePlaySimulated
            // 
            this.mnuGamePlaySimulated.Name = "mnuGamePlaySimulated";
            this.mnuGamePlaySimulated.Size = new System.Drawing.Size(186, 22);
            this.mnuGamePlaySimulated.Text = "Play Simulated &Game";
            this.mnuGamePlaySimulated.Click += new System.EventHandler(this.mnuGamePlaySimulated_Click);
            // 
            // mnuHelp
            // 
            this.mnuHelp.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuAppAbout});
            this.mnuHelp.Name = "mnuHelp";
            this.mnuHelp.Size = new System.Drawing.Size(44, 20);
            this.mnuHelp.Text = "&Help";
            // 
            // mnuAppAbout
            // 
            this.mnuAppAbout.Name = "mnuAppAbout";
            this.mnuAppAbout.Size = new System.Drawing.Size(177, 22);
            this.mnuAppAbout.Text = "&About showdown...";
            // 
            // ShowdownForm
            // 
            this.ClientSize = new System.Drawing.Size(720, 537);
            this.Controls.Add(this.btnNextatbat);
            this.Controls.Add(this.lblHomeatbat);
            this.Controls.Add(this.lblHomeerrors);
            this.Controls.Add(this.lblHomehits);
            this.Controls.Add(this.lblHomeinning1);
            this.Controls.Add(this.lblHomeinning10);
            this.Controls.Add(this.lblHomeinning2);
            this.Controls.Add(this.lblHomeinning3);
            this.Controls.Add(this.lblHomeinning4);
            this.Controls.Add(this.lblHomeinning5);
            this.Controls.Add(this.lblHomeinning6);
            this.Controls.Add(this.lblHomeinning7);
            this.Controls.Add(this.lblHomeinning8);
            this.Controls.Add(this.lblHomeinning9);
            this.Controls.Add(this.lblHomename);
            this.Controls.Add(this.lblHomeruns);
            this.Controls.Add(this.lblInning);
            this.Controls.Add(this.lblInning1);
            this.Controls.Add(this.lblInning10);
            this.Controls.Add(this.lblInning2);
            this.Controls.Add(this.lblInning3);
            this.Controls.Add(this.lblInning4);
            this.Controls.Add(this.lblInning5);
            this.Controls.Add(this.lblInning6);
            this.Controls.Add(this.lblInning7);
            this.Controls.Add(this.lblInning8);
            this.Controls.Add(this.lblInning9);
            this.Controls.Add(this.lblOuts);
            this.Controls.Add(this.lblStatic1);
            this.Controls.Add(this.lblStatic10);
            this.Controls.Add(this.lblStatic3);
            this.Controls.Add(this.lblStatic4);
            this.Controls.Add(this.lblStatic5);
            this.Controls.Add(this.lblViserrors);
            this.Controls.Add(this.lblVishits);
            this.Controls.Add(this.lblVisinning1);
            this.Controls.Add(this.lblVisinning10);
            this.Controls.Add(this.lblVisinning2);
            this.Controls.Add(this.lblVisinning3);
            this.Controls.Add(this.lblVisinning4);
            this.Controls.Add(this.lblVisinning5);
            this.Controls.Add(this.lblVisinning6);
            this.Controls.Add(this.lblVisinning7);
            this.Controls.Add(this.lblVisinning8);
            this.Controls.Add(this.lblVisinning9);
            this.Controls.Add(this.lblVisitatbat);
            this.Controls.Add(this.lblVisitname);
            this.Controls.Add(this.lblVisruns);
            this.Controls.Add(this.picStatic11);
            this.Controls.Add(this.grpStatic2);
            this.Controls.Add(this.mnuMainframe);
            this.Controls.Add(this.lblResult);
            this.Controls.Add(this.grpVislineup);
            this.Controls.Add(this.grpHomelineup);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Location = new System.Drawing.Point(0, 20);
            this.MainMenuStrip = this.mnuMainframe;
            this.Name = "ShowdownForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = " MLB Showdown";
            this.grpHomelineup.ResumeLayout(false);
            this.grpVislineup.ResumeLayout(false);
            this.grpStatic2.ResumeLayout(false);
            this.grpStatic2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picStatic11)).EndInit();
            this.mnuMainframe.ResumeLayout(false);
            this.mnuMainframe.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        } 
		#endregion

		private ToolStripMenuItem mnuGamePlaySimulated;
		private ToolStripMenuItem viewVisitingTeamMenuItem;
		private ToolStripMenuItem viewToolStripMenuItem;
        private ToolStripMenuItem autoPlayLogToolStripMenuItem;
		private ToolStripMenuItem resetSeasonStatsToolStripMenuItem;
        private ToolStripMenuItem selectTeamsToolStripMenuItem;
        private ToolStripMenuItem leagueToolStripMenuItem;
        private ToolStripMenuItem standingsToolStripMenuItem;
        private ToolStripMenuItem loadLeagueToolStripMenuItem;
        private ToolStripMenuItem teamsViewToolStripMenuItem;
        private ToolStripMenuItem topTenToolStripMenuItem;

	}
}
