
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

using DS.Showdown.ObjectLibrary;

namespace DS.Showdown.Game
{
	/// <summary>
	/// Summary description for ShowBatterForm.
	/// </summary>
	public partial class ShowBatterForm : System.Windows.Forms.Form
	{
		const int RESULT_STRIKEOUT = 0;
		const int RESULT_POPUP = 1;
		const int RESULT_GROUNDOUT = 2;
		const int RESULT_FLYOUT = 3;
		const int RESULT_WALK = 4;
		const int RESULT_SINGLE = 5;
		const int RESULT_SINGLEPLUS = 6;
		const int RESULT_DOUBLE = 7;
		const int RESULT_TRIPLE = 8;
		const int RESULT_HOMERUN = 9;
		Batter batter;

		public ShowBatterForm(Batter btr)
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			batter = btr;

			FillPlayerValues();
		}

		private void FillPlayerValues()
		{
			Position pos;
			int rating;

			// player info
			lblName.Text = batter.Name;
			lblOnbase.Text = batter.OnBase.ToString();
			lblSpeed.Text = batter.Speed.ToString();

			pos = batter.PrimaryPosition;
			rating = batter.PrimaryRating;

			if (pos == Position.None)
			{
				lblPosition1.Text = "--";
			}
			else
			{
				lblPosition1.Text = String.Format("{0} {1}{2}", EnumHelpers.PositionToString(pos), rating == 0 ? "" : "+",
					rating);
			}

			pos = batter.SecondaryPosition;
			rating = batter.SecondaryRating;

			if (pos == Position.None)
			{
				lblPosition2.Text = "--";
			}
			else
			{
				lblPosition2.Text = String.Format("{0} {1}{2}", EnumHelpers.PositionToString(pos), rating == 0 ? "" : "+",
					rating);
			}


			lblBats.Text = EnumHelpers.BattingSideToString(batter.BattingSide);

			lblPoints.Text = batter.Points.ToString();

			// outcomes table
			lblRangeso.Text = batter.GetResultRange(RESULT_STRIKEOUT);
			lblRangefo.Text = batter.GetResultRange(RESULT_FLYOUT);
			lblRangepu.Text = batter.GetResultRange(RESULT_POPUP);
			lblRangegb.Text = batter.GetResultRange(RESULT_GROUNDOUT);
			lblRangew.Text = batter.GetResultRange(RESULT_WALK);
			lblRange1b.Text = batter.GetResultRange(RESULT_SINGLE);
			lblRange1bplus.Text = batter.GetResultRange(RESULT_SINGLEPLUS);
			lblRange2b.Text = batter.GetResultRange(RESULT_DOUBLE);
			lblRange3b.Text = batter.GetResultRange(RESULT_TRIPLE);
			lblRangehr.Text = batter.GetResultRange(RESULT_HOMERUN);

			// season stats
			lblAbseason.Text = batter.SeasonStats.AtBats.ToString();
			lblHseason.Text = batter.SeasonStats.Hits.ToString();
			lblRseason.Text = batter.SeasonStats.RunsScored.ToString();
			lbl2bseason.Text = batter.SeasonStats.Doubles.ToString();
			lbl3bseason.Text = batter.SeasonStats.Triples.ToString();
			lblHrseason.Text = batter.SeasonStats.HomeRuns.ToString();
			lblRbiseason.Text = batter.SeasonStats.RBIs.ToString();
			lblKseason.Text = batter.SeasonStats.StrikeOuts.ToString();
			lblBbseason.Text = batter.SeasonStats.Walks.ToString();
			lblSacseason.Text = 
				(batter.SeasonStats.SacFlies + batter.SeasonStats.SacBunts).ToString();
			lblSbseason.Text = batter.SeasonStats.Steals.ToString();


			lblAvgseason.Text = String.Format("{0,4:F3}", batter.SeasonStats.BattingAvg);
			lblObpseason.Text = String.Format("{0,4:F3}", batter.SeasonStats.OnBasePct);
			lblSlugseason.Text = String.Format("{0,4:F3}", batter.SeasonStats.SluggingPct);

			// game stats
			lblAbgame.Text = batter.GameStats.AtBats.ToString();
			lblHgame.Text = batter.GameStats.Hits.ToString();
			lblRgame.Text = batter.GameStats.RunsScored.ToString();
			lbl2bgame.Text = batter.GameStats.Doubles.ToString();
			lbl3bgame.Text = batter.GameStats.Triples.ToString();
			lblHrgame.Text = batter.GameStats.HomeRuns.ToString();
			lblRbigame.Text = batter.GameStats.RBIs.ToString();
			lblKgame.Text = batter.GameStats.StrikeOuts.ToString();
			lblBbgame.Text = batter.GameStats.Walks.ToString();
			lblSacgame.Text =
				(batter.GameStats.SacFlies + batter.GameStats.SacBunts).ToString();
			lblSbgame.Text = batter.GameStats.Steals.ToString();

			lblAvggame.Text = String.Format("{0,4:F3}", batter.GameStats.BattingAvg);
			lblObpgame.Text = String.Format("{0,4:F3}", batter.GameStats.OnBasePct);
			lblSluggame.Text = String.Format("{0,4:F3}", batter.GameStats.SluggingPct);

		}

	}
}
